// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_symbolFormation.v
// Created: 2023-05-02 12:36:36
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_symbolFormation
// Source Path: 
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_symbolFormation
          (clk,
           reset,
           enb_1_32_0,
           tmp_re,
           tmp_im,
           tmp,
           varargout_1_re,
           varargout_1_im,
           varargout_2);


  input   clk;
  input   reset;
  input   enb_1_32_0;
  input   signed [15:0] tmp_re;  // sfix16_En14
  input   signed [15:0] tmp_im;  // sfix16_En14
  input   tmp;
  output  signed [15:0] varargout_1_re;  // sfix16_En14
  output  signed [15:0] varargout_1_im;  // sfix16_En14
  output  varargout_2;


  reg  obj_symbolFormationObj_validInRegDelay2;
  reg  obj_symbolFormationObj_validInRegDelay1;
  reg  obj_symbolFormationObj_validInReg;
  wire [7:0] obj_symbolFormationObj_FFTLenRegDelay2;  // ufix8
  reg [7:0] obj_symbolFormationObj_FFTLenRegDelay2_1;  // ufix8
  reg [7:0] obj_symbolFormationObj_FFTLenRegDelay1;  // ufix8
  wire [7:0] obj_symbolFormationObj_numLgScRegDelay2;  // ufix8
  wire [7:0] obj_symbolFormationObj_numRgScRegDelay2;  // ufix8
  wire [7:0] tmp_1;  // ufix8
  reg [7:0] obj_symbolFormationObj_sumLgRg;  // ufix8
  wire [7:0] obj_symbolFormationObj_insertDC;  // ufix8
  wire [7:0] tmp_2;  // ufix8
  reg [7:0] obj_symbolFormationObj_sumLgRgDC;  // ufix8
  wire [7:0] tmp_3;  // ufix8
  reg [7:0] obj_symbolFormationObj_numDataSc;  // ufix8
  wire [7:0] tmp_4;  // ufix8
  wire [7:0] obj_symbolFormationObj_inCount;  // ufix8
  reg [7:0] obj_symbolFormationObj_inCount_1;  // ufix8
  wire [7:0] tmp_5;  // ufix8
  wire tmp_6;
  reg [7:0] obj_symbolFormationObj_numDataScMinusVecLen;  // ufix8
  wire [7:0] tmp_7;  // ufix8
  wire [7:0] tmp_8;  // ufix8
  wire tmp_9;
  wire [7:0] tmp_10;  // ufix8
  wire [7:0] tmp_11;  // ufix8
  wire tmp_12;
  reg  obj_symbolFormationObj_RAM2WriteSelect;
  wire tmp_13;
  wire tmp_14;
  wire tmp_15;
  wire tmp_16;
  wire out;
  wire out_1;
  wire tmp_17;
  reg  obj_symbolFormationObj_writeEnbRAM1;
  wire tmp_18;
  wire out_2;
  wire out_3;
  wire tmp_19;
  reg  obj_symbolFormationObj_writeEnbRAM2;
  wire tmp_20;
  reg [7:0] obj_symbolFormationObj_FFTLenReg;  // ufix8
  wire [7:0] tmp_21;  // ufix8
  reg [7:0] obj_symbolFormationObj_FFTLenMinusVecLen;  // ufix8
  wire [7:0] tmp_22;  // ufix8
  wire [7:0] tmp_23;  // ufix8
  wire [7:0] obj_symbolFormationObj_outCount;  // ufix8
  wire obj_symbolFormationObj_startSymbForm;
  wire obj_symbolFormationObj_sym1Done;
  reg [7:0] obj_symbolFormationObj_inCountReg;  // ufix8
  wire tmp_24;
  wire obj_symbolFormationObj_sym1Done_1;
  wire obj_symbolFormationObj_sym2Done;
  wire tmp_25;
  wire obj_symbolFormationObj_sym2Done_1;
  wire obj_symbolFormationObj_startSymbForm_1;
  wire tmp_26;
  wire tmp_27;
  reg  obj_symbolFormationObj_sym2Done_2;
  wire tmp_28;
  reg  obj_symbolFormationObj_sym1Done_2;
  wire tmp_29;
  wire tmp_30;
  wire tmp_31;
  wire tmp_32;
  reg [7:0] obj_symbolFormationObj_outCount_1;  // ufix8
  wire [7:0] tmp_33;  // ufix8
  wire [7:0] tmp_34;  // ufix8
  reg [7:0] obj_symbolFormationObj_FFTLenMinusVecLenReg;  // ufix8
  wire tmp_35;
  wire tmp_36;
  wire [7:0] tmp_37;  // ufix8
  reg  obj_symbolFormationObj_startSymbForm_2;
  wire [7:0] tmp_38;  // ufix8
  wire tmp_39;
  wire tmp_40;
  wire tmp_41;
  wire tmp_42;
  wire tmp_43;
  wire tmp_44;
  wire tmp_45;
  wire tmp_46;
  wire tmp_47;
  wire tmp_48;
  reg  obj_symbolFormationObj_startSymbFormReg;
  reg  obj_symbolFormationObj_startSymbFormReg1;
  reg  obj_symbolFormationObj_startSymbFormReg2;
  wire obj_symbolFormationObj_sendOutput;
  wire obj_symbolFormationObj_sendOutput_1;
  wire tmp_49;
  reg  obj_symbolFormationObj_sendOutput_2;
  wire signed [15:0] obj_symbolFormationObj_dataOutReg_re;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_dataOutReg_im;  // sfix16_En14
  reg [7:0] obj_symbolFormationObj_outCountReg;  // ufix8
  reg [7:0] obj_symbolFormationObj_outCountReg1;  // ufix8
  reg [7:0] obj_symbolFormationObj_outCountReg2;  // ufix8
  wire tmp_50;
  wire tmp_51;
  reg [7:0] obj_symbolFormationObj_numLgScRegDelay2_1;  // ufix8
  reg [7:0] obj_symbolFormationObj_numLgScRegDelay1;  // ufix8
  reg [7:0] obj_symbolFormationObj_numLgScReg;  // ufix8
  reg [7:0] obj_symbolFormationObj_numLgScSampled;  // ufix8
  wire [7:0] tmp_52;  // ufix8
  wire [7:0] tmp_53;  // ufix8
  wire [7:0] tmp_54;  // ufix8
  reg [7:0] obj_symbolFormationObj_numLgScSampledReg;  // ufix8
  reg [7:0] obj_symbolFormationObj_numLgScOutReg1;  // ufix8
  reg [7:0] obj_symbolFormationObj_numLgScOutReg2;  // ufix8
  reg [7:0] obj_symbolFormationObj_numLgScOutReg3;  // ufix8
  wire tmp_55;
  wire tmp_56;
  wire [7:0] tmp_57;  // ufix8
  wire [7:0] tmp_58;  // ufix8
  reg [7:0] obj_symbolFormationObj_numDataScPlusNumLgScReg;  // ufix8
  reg [7:0] obj_symbolFormationObj_numDataScPlusNumLgScReg1;  // ufix8
  reg [7:0] obj_symbolFormationObj_numDataScPlusNumLgScReg2;  // ufix8
  wire tmp_59;
  wire tmp_60;
  wire tmp_61;
  reg [7:0] obj_symbolFormationObj_FFTSampled;  // ufix8
  wire [7:0] tmp_62;  // ufix8
  wire [7:0] tmp_63;  // ufix8
  wire tmp_64;
  reg [7:0] obj_symbolFormationObj_numRgScRegDelay2_1;  // ufix8
  reg [7:0] obj_symbolFormationObj_numRgScRegDelay1;  // ufix8
  reg [7:0] obj_symbolFormationObj_numRgScReg;  // ufix8
  reg [7:0] obj_symbolFormationObj_numRgScSampled;  // ufix8
  wire [7:0] tmp_65;  // ufix8
  wire [7:0] tmp_66;  // ufix8
  wire [7:0] tmp_67;  // ufix8
  wire [7:0] tmp_68;  // ufix8
  reg [7:0] obj_symbolFormationObj_FFTLenMinusNumRgScReg;  // ufix8
  wire tmp_69;
  wire tmp_70;
  wire tmp_71;
  wire [7:0] obj_symbolFormationObj_numLgScCountReg;  // ufix8
  wire [7:0] obj_symbolFormationObj_numLgScCountReg_1;  // ufix8
  reg [7:0] obj_symbolFormationObj_numLgScCount;  // ufix8
  wire [7:0] tmp_72;  // ufix8
  wire [7:0] tmp_73;  // ufix8
  wire tmp_74;
  wire [7:0] tmp_75;  // ufix8
  wire tmp_76;
  wire [7:0] tmp_77;  // ufix8
  wire [7:0] tmp_78;  // ufix8
  wire [7:0] tmp_79;  // ufix8
  reg [7:0] obj_symbolFormationObj_numLgScCountReg_2;  // ufix8
  wire tmp_80;
  wire [7:0] obj_symbolFormationObj_numSampLeft;  // ufix8
  wire tmp_81;
  wire [7:0] obj_symbolFormationObj_numSampLeft_1;  // ufix8
  wire [7:0] tmp_82;  // ufix8
  reg [7:0] obj_symbolFormationObj_insertDC_1;  // ufix8
  wire tmp_83;
  wire [7:0] tmp_84;  // ufix8
  wire [7:0] tmp_85;  // ufix8
  wire [7:0] tmp_86;  // ufix8
  reg [7:0] obj_symbolFormationObj_numSampLeft_2;  // ufix8
  wire [7:0] tmp_87;  // ufix8
  wire [7:0] tmp_88;  // ufix8
  wire [7:0] tmp_89;  // ufix8
  reg [7:0] obj_symbolFormationObj_maxLimitForDataReg;  // ufix8
  reg [7:0] obj_symbolFormationObj_maxLimitForDataReg1;  // ufix8
  reg [7:0] obj_symbolFormationObj_maxLimitForDataReg2;  // ufix8
  wire tmp_90;
  wire out_4;
  wire out_5;
  wire out_6;
  wire tmp_91;
  wire tmp_92;
  reg  obj_symbolFormationObj_enbDataPlacing;
  wire obj_symbolFormationObj_sendDC;
  wire tmp_93;
  wire [7:0] tmp_94;  // ufix8
  reg [7:0] obj_symbolFormationObj_FFTLenBy2;  // ufix8
  wire [7:0] tmp_95;  // ufix8
  reg [7:0] obj_symbolFormationObj_FFTLenBy2Reg;  // ufix8
  reg [7:0] obj_symbolFormationObj_FFTLenBy2Reg1;  // ufix8
  reg [7:0] obj_symbolFormationObj_FFTLenBy2Reg2;  // ufix8
  reg [7:0] obj_symbolFormationObj_FFTLenBy2Reg3;  // ufix8
  wire tmp_96;
  wire obj_symbolFormationObj_sendDC_1;
  wire obj_symbolFormationObj_sendDC_2;
  wire tmp_97;
  wire tmp_98;
  wire obj_symbolFormationObj_sendDC_3;
  wire tmp_99;
  reg  obj_symbolFormationObj_sendDC_4;
  wire tmp_100;
  wire tmp_101;
  reg [7:0] obj_symbolFormationObj_FFTLenMinusVecLenReg1;  // ufix8
  reg [7:0] obj_symbolFormationObj_FFTLenMinusVecLenReg2;  // ufix8
  reg [7:0] obj_symbolFormationObj_FFTLenMinusVecLenReg3;  // ufix8
  wire tmp_102;
  wire [7:0] obj_symbolFormationObj_prevVecSamples;  // ufix8
  wire tmp_103;
  wire [7:0] obj_symbolFormationObj_prevVecSamples_1;  // ufix8
  reg [7:0] obj_symbolFormationObj_numLgScCountReg1;  // ufix8
  reg [7:0] obj_symbolFormationObj_numLgScCountReg2;  // ufix8
  reg [7:0] obj_symbolFormationObj_numLgScCountReg3;  // ufix8
  wire tmp_104;
  wire [7:0] obj_symbolFormationObj_prevVecSamples_2;  // ufix8
  wire tmp_105;
  wire [7:0] tmp_106;  // ufix8
  wire [7:0] obj_symbolFormationObj_prevVecSamples_3;  // ufix8
  reg [7:0] obj_symbolFormationObj_prevVecSamples_4;  // ufix8
  wire [7:0] tmp_107;  // ufix8
  wire [7:0] tmp_108;  // ufix8
  wire [7:0] tmp_109;  // ufix8
  wire [7:0] tmp_110;  // ufix8
  wire [7:0] tmp_111;  // ufix8
  wire [7:0] tmp_112;  // ufix8
  wire tmp_113;
  wire [7:0] obj_symbolFormationObj_dataVec1Samples;  // ufix8
  wire tmp_114;
  wire [7:0] obj_symbolFormationObj_dataVec1Samples_1;  // ufix8
  wire [7:0] tmp_115;  // ufix8
  wire [7:0] tmp_116;  // ufix8
  wire [7:0] tmp_117;  // ufix8
  reg [7:0] obj_symbolFormationObj_dataVec1Samples_2;  // ufix8
  wire [7:0] tmp_118;  // ufix8
  wire tmp_119;
  wire tmp_120;
  wire signed [15:0] obj_symbolFormationObj_dataVec2_re;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_dataVec2_im;  // sfix16_En14
  wire tmp_121;
  wire tmp_122;
  wire out_7;
  wire out_8;
  wire out_9;
  wire tmp_123;
  wire tmp_124;
  wire obj_symbolFormationObj_startRead;
  wire tmp_125;
  wire obj_symbolFormationObj_startRead_1;
  wire tmp_126;
  wire obj_symbolFormationObj_startRead_2;
  wire tmp_127;
  wire tmp_128;
  wire obj_symbolFormationObj_startRead_3;
  wire tmp_129;
  wire obj_symbolFormationObj_startRead_4;
  wire tmp_130;
  wire tmp_131;
  reg  obj_symbolFormationObj_startRead_5;
  wire tmp_132;
  reg  obj_symbolFormationObj_startReadFromRAM;
  wire tmp_133;
  wire tmp_134;
  wire [7:0] obj_symbolFormationObj_CPLenRegDelay2;  // ufix8
  reg [7:0] obj_symbolFormationObj_CPLenRegDelay2_1;  // ufix8
  reg [7:0] obj_symbolFormationObj_CPLenRegDelay1;  // ufix8
  reg [7:0] obj_symbolFormationObj_CPLenReg;  // ufix8
  reg [7:0] obj_symbolFormationObj_CPSampled;  // ufix8
  wire [7:0] tmp_135;  // ufix8
  wire [7:0] tmp_136;  // ufix8
  wire [7:0] tmp_137;  // ufix8
  reg [7:0] obj_symbolFormationObj_CPSampledReg;  // ufix8
  wire tmp_138;
  wire tmp_139;
  reg  obj_symbolFormationObj_selectRAM;
  wire tmp_140;
  wire tmp_141;
  wire tmp_142;
  reg  obj_symbolFormationObj_selectRAMReg;
  reg  obj_symbolFormationObj_selectRAMReg1;
  wire tmp_143;
  reg  obj_symbolFormationObj_RAM2ReadSelect;
  wire tmp_144;
  reg signed [15:0] obj_symbolFormationObj_dataInRegDelay2_re;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataInRegDelay2_im;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataInRegDelay1_re;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataInRegDelay1_im;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataInReg_re;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataInReg_im;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataInReg1_re;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataInReg1_im;  // sfix16_En14
  wire tmp_145;
  wire [8:0] obj_symbolFormationObj_writeAddrRAM2;  // ufix9
  reg [8:0] obj_symbolFormationObj_writeAddrRAM2_1;  // ufix9
  wire [8:0] tmp_146;  // ufix9
  wire [8:0] tmp_147;  // ufix9
  wire [8:0] tmp_148;  // ufix9
  wire [8:0] tmp_149;  // ufix9
  wire tmp_150;
  wire tmp_151;
  wire tmp_152;
  wire [7:0] tmp_153;  // ufix8
  reg [7:0] obj_symbolFormationObj_numDataScMinusVecLenReg;  // ufix8
  wire [7:0] obj_symbolFormationObj_readCount;  // ufix8
  reg [7:0] obj_symbolFormationObj_readCount_1;  // ufix8
  wire [7:0] tmp_154;  // ufix8
  wire tmp_155;
  wire [7:0] tmp_156;  // ufix8
  wire [7:0] tmp_157;  // ufix8
  wire tmp_158;
  wire [8:0] obj_symbolFormationObj_readAddr;  // ufix9
  reg [8:0] obj_symbolFormationObj_readAddr_1;  // ufix9
  wire [8:0] tmp_159;  // ufix9
  wire [8:0] tmp_160;  // ufix9
  wire [8:0] tmp_161;  // ufix9
  wire signed [15:0] tmp_re_1;  // sfix16_En14
  wire signed [15:0] tmp_im_1;  // sfix16_En14
  wire tmp_162;
  wire [8:0] obj_symbolFormationObj_writeAddrRAM1;  // ufix9
  reg [8:0] obj_symbolFormationObj_writeAddrRAM1_1;  // ufix9
  wire [8:0] tmp_163;  // ufix9
  wire [8:0] tmp_164;  // ufix9
  wire [8:0] tmp_165;  // ufix9
  wire signed [15:0] tmp_re_2;  // sfix16_En14
  wire signed [15:0] tmp_im_2;  // sfix16_En14
  wire signed [15:0] tmp_re_3;  // sfix16_En14
  wire signed [15:0] tmp_im_3;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataOutRAM_re;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataOutRAM_im;  // sfix16_En14
  wire signed [15:0] tmp_re_4;  // sfix16_En14
  wire signed [15:0] tmp_im_4;  // sfix16_En14
  wire signed [15:0] tmp_re_5;  // sfix16_En14
  wire signed [15:0] tmp_im_5;  // sfix16_En14
  wire tmp_166;
  wire tmp_167;
  wire signed [15:0] obj_symbolFormationObj_dataVec2_re_1;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_dataVec2_im_1;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_dataVec2_re_2;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_dataVec2_im_2;  // sfix16_En14
  wire signed [15:0] tmp_re_6;  // sfix16_En14
  wire signed [15:0] tmp_im_6;  // sfix16_En14
  wire signed [15:0] tmp_re_7;  // sfix16_En14
  wire signed [15:0] tmp_im_7;  // sfix16_En14
  wire signed [15:0] tmp_re_8;  // sfix16_En14
  wire signed [15:0] tmp_im_8;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataVec2_re_3;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataVec2_im_3;  // sfix16_En14
  wire signed [15:0] tmp_re_9;  // sfix16_En14
  wire signed [15:0] tmp_im_9;  // sfix16_En14
  wire tmp_168;
  wire tmp_169;
  wire signed [15:0] obj_symbolFormationObj_prevVecData_re;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_prevVecData_im;  // sfix16_En14
  wire signed [15:0] tmp_re_10;  // sfix16_En14
  wire signed [15:0] tmp_im_10;  // sfix16_En14
  wire tmp_170;
  wire signed [15:0] obj_symbolFormationObj_prevVecData_re_1;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_prevVecData_im_1;  // sfix16_En14
  wire signed [15:0] tmp_re_11;  // sfix16_En14
  wire signed [15:0] tmp_im_11;  // sfix16_En14
  wire signed [15:0] tmp_re_12;  // sfix16_En14
  wire signed [15:0] tmp_im_12;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_prevVecData_re_2;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_prevVecData_im_2;  // sfix16_En14
  wire signed [15:0] tmp_re_13;  // sfix16_En14
  wire signed [15:0] tmp_im_13;  // sfix16_En14
  wire signed [15:0] tmp_re_14;  // sfix16_En14
  wire signed [15:0] tmp_im_14;  // sfix16_En14
  wire tmp_171;
  wire tmp_172;
  wire signed [15:0] obj_symbolFormationObj_dataVec1_re;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_dataVec1_im;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_dataVec1_re_1;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_dataVec1_im_1;  // sfix16_En14
  wire signed [15:0] tmp_re_15;  // sfix16_En14
  wire signed [15:0] tmp_im_15;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_dataVec1_re_2;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_dataVec1_im_2;  // sfix16_En14
  wire signed [15:0] tmp_re_16;  // sfix16_En14
  wire signed [15:0] tmp_im_16;  // sfix16_En14
  wire signed [15:0] tmp_re_17;  // sfix16_En14
  wire signed [15:0] tmp_im_17;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataVec1_re_3;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataVec1_im_3;  // sfix16_En14
  wire signed [15:0] tmp_re_18;  // sfix16_En14
  wire signed [15:0] tmp_im_18;  // sfix16_En14
  wire signed [15:0] tmp_re_19;  // sfix16_En14
  wire signed [15:0] tmp_im_19;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_dataOutReg_re_1;  // sfix16_En14
  wire signed [15:0] obj_symbolFormationObj_dataOutReg_im_1;  // sfix16_En14
  wire signed [15:0] tmp_re_20;  // sfix16_En14
  wire signed [15:0] tmp_im_20;  // sfix16_En14
  wire signed [15:0] tmp_re_21;  // sfix16_En14
  wire signed [15:0] tmp_im_21;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataOutReg_re_2;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataOutReg_im_2;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataOut_re;  // sfix16_En14
  reg signed [15:0] obj_symbolFormationObj_dataOut_im;  // sfix16_En14
  wire obj_symbolFormationObj_validOutReg;
  wire obj_symbolFormationObj_validOutReg_1;
  wire tmp_173;
  reg  obj_symbolFormationObj_validOutReg_2;
  reg  obj_symbolFormationObj_validOut;


  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_validInRegDelay2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_validInRegDelay2 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_validInRegDelay2 <= tmp;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_validInRegDelay1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_validInRegDelay1 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_validInRegDelay1 <= obj_symbolFormationObj_validInRegDelay2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_validInReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_validInReg <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_validInReg <= obj_symbolFormationObj_validInRegDelay1;
        end
      end
    end



  assign obj_symbolFormationObj_FFTLenRegDelay2 = 8'b10000000;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenRegDelay2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenRegDelay2_1 <= 8'b01000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenRegDelay2_1 <= obj_symbolFormationObj_FFTLenRegDelay2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenRegDelay1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenRegDelay1 <= 8'b01000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenRegDelay1 <= obj_symbolFormationObj_FFTLenRegDelay2_1;
        end
      end
    end



  assign obj_symbolFormationObj_numLgScRegDelay2 = 8'b00011100;



  assign obj_symbolFormationObj_numRgScRegDelay2 = 8'b00011011;



  assign tmp_1 = obj_symbolFormationObj_numLgScRegDelay2 + obj_symbolFormationObj_numRgScRegDelay2;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_sumLgRg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_sumLgRg <= 8'b00001011;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_sumLgRg <= tmp_1;
        end
      end
    end



  assign obj_symbolFormationObj_insertDC = 8'b00000001;



  assign tmp_2 = obj_symbolFormationObj_sumLgRg + obj_symbolFormationObj_insertDC;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_sumLgRgDC_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_sumLgRgDC <= 8'b00001011;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_sumLgRgDC <= tmp_2;
        end
      end
    end



  assign tmp_3 = obj_symbolFormationObj_FFTLenRegDelay1 - obj_symbolFormationObj_sumLgRgDC;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numDataSc_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numDataSc <= 8'b01000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numDataSc <= tmp_3;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp609
  assign tmp_4 = obj_symbolFormationObj_numDataSc - 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp127
  assign obj_symbolFormationObj_inCount = 8'b00000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp127
  assign tmp_5 = obj_symbolFormationObj_inCount_1 + 8'b00000001;



  assign tmp_6 = obj_symbolFormationObj_inCount_1 == 8'b00000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp132
  assign tmp_7 = (tmp_6 == 1'b0 ? obj_symbolFormationObj_numDataScMinusVecLen :
              tmp_4);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp484
  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numDataScMinusVecLen_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numDataScMinusVecLen <= 8'b01000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numDataScMinusVecLen <= tmp_8;
        end
      end
    end



  assign tmp_8 = (obj_symbolFormationObj_validInReg == 1'b0 ? obj_symbolFormationObj_numDataScMinusVecLen :
              tmp_7);



  assign tmp_9 = obj_symbolFormationObj_inCount_1 >= tmp_8;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp121
  assign tmp_10 = (tmp_9 == 1'b0 ? tmp_5 :
              obj_symbolFormationObj_inCount);



  assign tmp_11 = (obj_symbolFormationObj_validInReg == 1'b0 ? obj_symbolFormationObj_inCount_1 :
              tmp_10);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_inCount_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_inCount_1 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_inCount_1 <= tmp_11;
        end
      end
    end



  assign tmp_12 = obj_symbolFormationObj_inCount_1 >= tmp_8;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp124
  assign tmp_13 =  ! obj_symbolFormationObj_RAM2WriteSelect;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp117
  assign tmp_14 = (tmp_12 == 1'b0 ? obj_symbolFormationObj_RAM2WriteSelect :
              tmp_13);



  assign tmp_15 = (obj_symbolFormationObj_validInReg == 1'b0 ? obj_symbolFormationObj_RAM2WriteSelect :
              tmp_14);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_RAM2WriteSelect_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_RAM2WriteSelect <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_RAM2WriteSelect <= tmp_15;
        end
      end
    end



  assign tmp_16 = obj_symbolFormationObj_validInReg && ( ! obj_symbolFormationObj_RAM2WriteSelect);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp163
  assign out = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp163
  assign out_1 = 1'b1;



  assign tmp_17 = (tmp_16 == 1'b0 ? out :
              out_1);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_writeEnbRAM1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_writeEnbRAM1 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_writeEnbRAM1 <= tmp_17;
        end
      end
    end



  assign tmp_18 = obj_symbolFormationObj_validInReg && obj_symbolFormationObj_RAM2WriteSelect;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp158
  assign out_2 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp158
  assign out_3 = 1'b1;



  assign tmp_19 = (tmp_18 == 1'b0 ? out_2 :
              out_3);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_writeEnbRAM2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_writeEnbRAM2 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_writeEnbRAM2 <= tmp_19;
        end
      end
    end



  assign tmp_20 = obj_symbolFormationObj_inCount_1 == 8'b00000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp615
  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenReg <= 8'b01000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenReg <= obj_symbolFormationObj_FFTLenRegDelay1;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp612
  assign tmp_21 = obj_symbolFormationObj_FFTLenReg - 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp136
  assign tmp_22 = (tmp_20 == 1'b0 ? obj_symbolFormationObj_FFTLenMinusVecLen :
              tmp_21);



  assign tmp_23 = (obj_symbolFormationObj_validInReg == 1'b0 ? obj_symbolFormationObj_FFTLenMinusVecLen :
              tmp_22);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp488
  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenMinusVecLen_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenMinusVecLen <= 8'b01000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenMinusVecLen <= tmp_23;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp471
  assign obj_symbolFormationObj_outCount = 8'b00000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp468
  assign obj_symbolFormationObj_startSymbForm = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp635
  assign obj_symbolFormationObj_sym1Done = 1'b0;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_inCountReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_inCountReg <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_inCountReg <= obj_symbolFormationObj_inCount_1;
        end
      end
    end



  assign tmp_24 = obj_symbolFormationObj_inCountReg >= obj_symbolFormationObj_numDataScMinusVecLen;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp183
  assign obj_symbolFormationObj_sym1Done_1 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp638
  assign obj_symbolFormationObj_sym2Done = 1'b0;



  assign tmp_25 = obj_symbolFormationObj_inCountReg >= obj_symbolFormationObj_numDataScMinusVecLen;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp196
  assign obj_symbolFormationObj_sym2Done_1 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp210
  assign obj_symbolFormationObj_startSymbForm_1 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp190
  assign tmp_27 = (tmp_25 == 1'b0 ? tmp_26 :
              obj_symbolFormationObj_sym2Done_1);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp632
  assign tmp_28 = (obj_symbolFormationObj_sym2Done_2 == 1'b0 ? obj_symbolFormationObj_sym2Done_2 :
              obj_symbolFormationObj_sym2Done);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp203
  assign tmp_29 = (obj_symbolFormationObj_sym1Done_2 == 1'b0 ? tmp_28 :
              obj_symbolFormationObj_sym2Done_2);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp176
  assign tmp_31 = (tmp_24 == 1'b0 ? tmp_30 :
              obj_symbolFormationObj_sym1Done_1);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp206
  assign tmp_32 = (obj_symbolFormationObj_sym1Done_2 == 1'b0 ? obj_symbolFormationObj_sym1Done_2 :
              obj_symbolFormationObj_sym1Done);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp471
  assign tmp_33 = obj_symbolFormationObj_outCount_1 + 8'b00000001;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenMinusVecLenReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenMinusVecLenReg <= 8'b01000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenMinusVecLenReg <= tmp_34;
        end
      end
    end



  assign tmp_35 = obj_symbolFormationObj_outCount_1 == 8'b00000000;



  assign tmp_34 = (tmp_35 == 1'b0 ? obj_symbolFormationObj_FFTLenMinusVecLenReg :
              obj_symbolFormationObj_FFTLenMinusVecLen);



  assign tmp_36 = obj_symbolFormationObj_outCount_1 == tmp_34;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp235
  assign tmp_37 = (tmp_36 == 1'b0 ? tmp_33 :
              obj_symbolFormationObj_outCount);



  assign tmp_38 = (obj_symbolFormationObj_startSymbForm_2 == 1'b0 ? obj_symbolFormationObj_outCount_1 :
              tmp_37);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_outCount_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_outCount_1 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_outCount_1 <= tmp_38;
        end
      end
    end



  assign tmp_39 = obj_symbolFormationObj_outCount_1 == tmp_34;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp231
  assign tmp_40 = (tmp_39 == 1'b0 ? obj_symbolFormationObj_startSymbForm_2 :
              obj_symbolFormationObj_startSymbForm);



  assign tmp_41 = (obj_symbolFormationObj_startSymbForm_2 == 1'b0 ? obj_symbolFormationObj_startSymbForm_2 :
              tmp_40);



  assign tmp_42 = (obj_symbolFormationObj_sym2Done_2 || obj_symbolFormationObj_sym1Done_2) && ( ! tmp_41);



  assign tmp_30 = (tmp_42 == 1'b0 ? obj_symbolFormationObj_sym1Done_2 :
              tmp_32);



  assign tmp_43 = (obj_symbolFormationObj_writeEnbRAM1 == 1'b0 ? tmp_30 :
              tmp_31);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_sym1Done_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_sym1Done_2 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_sym1Done_2 <= tmp_43;
        end
      end
    end



  assign tmp_44 = (obj_symbolFormationObj_sym2Done_2 || obj_symbolFormationObj_sym1Done_2) && ( ! tmp_41);



  assign tmp_26 = (tmp_44 == 1'b0 ? obj_symbolFormationObj_sym2Done_2 :
              tmp_29);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp168
  assign tmp_45 = (obj_symbolFormationObj_writeEnbRAM2 == 1'b0 ? tmp_26 :
              tmp_27);



  assign tmp_46 = (obj_symbolFormationObj_writeEnbRAM1 == 1'b0 ? tmp_45 :
              tmp_26);



  // HDL code generation from MATLAB function: SystemCore_stepImpl
  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_sym2Done_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_sym2Done_2 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_sym2Done_2 <= tmp_46;
        end
      end
    end



  assign tmp_47 = (obj_symbolFormationObj_sym2Done_2 || obj_symbolFormationObj_sym1Done_2) && ( ! tmp_41);



  assign tmp_48 = (tmp_47 == 1'b0 ? tmp_41 :
              obj_symbolFormationObj_startSymbForm_1);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_startSymbForm_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_startSymbForm_2 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_startSymbForm_2 <= tmp_48;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_startSymbFormReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_startSymbFormReg <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_startSymbFormReg <= obj_symbolFormationObj_startSymbForm_2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_startSymbFormReg1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_startSymbFormReg1 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_startSymbFormReg1 <= obj_symbolFormationObj_startSymbFormReg;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_startSymbFormReg2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_startSymbFormReg2 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_startSymbFormReg2 <= obj_symbolFormationObj_startSymbFormReg1;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp308
  assign obj_symbolFormationObj_sendOutput = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp308
  assign obj_symbolFormationObj_sendOutput_1 = 1'b1;



  assign tmp_49 = (obj_symbolFormationObj_startSymbFormReg2 == 1'b0 ? obj_symbolFormationObj_sendOutput :
              obj_symbolFormationObj_sendOutput_1);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_sendOutput_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_sendOutput_2 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_sendOutput_2 <= tmp_49;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp313
  assign obj_symbolFormationObj_dataOutReg_re = 16'sb0000000000000000;
  assign obj_symbolFormationObj_dataOutReg_im = 16'sb0000000000000000;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_outCountReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_outCountReg <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_outCountReg <= obj_symbolFormationObj_outCount_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_outCountReg1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_outCountReg1 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_outCountReg1 <= obj_symbolFormationObj_outCountReg;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_outCountReg2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_outCountReg2 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_outCountReg2 <= obj_symbolFormationObj_outCountReg1;
        end
      end
    end



  assign tmp_50 = obj_symbolFormationObj_outCount_1 == 8'b00000000;



  assign tmp_51 = obj_symbolFormationObj_inCount_1 == 8'b00000000;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numLgScRegDelay2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numLgScRegDelay2_1 <= 8'b00000110;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numLgScRegDelay2_1 <= obj_symbolFormationObj_numLgScRegDelay2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numLgScRegDelay1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numLgScRegDelay1 <= 8'b00000110;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numLgScRegDelay1 <= obj_symbolFormationObj_numLgScRegDelay2_1;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp621
  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numLgScReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numLgScReg <= 8'b00000110;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numLgScReg <= obj_symbolFormationObj_numLgScRegDelay1;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp148
  assign tmp_52 = (tmp_51 == 1'b0 ? obj_symbolFormationObj_numLgScSampled :
              obj_symbolFormationObj_numLgScReg);



  assign tmp_53 = (obj_symbolFormationObj_validInReg == 1'b0 ? obj_symbolFormationObj_numLgScSampled :
              tmp_52);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp500
  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numLgScSampled_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numLgScSampled <= 8'b00000110;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numLgScSampled <= tmp_53;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numLgScSampledReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numLgScSampledReg <= 8'b00000110;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numLgScSampledReg <= tmp_54;
        end
      end
    end



  assign tmp_54 = (tmp_50 == 1'b0 ? obj_symbolFormationObj_numLgScSampledReg :
              obj_symbolFormationObj_numLgScSampled);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numLgScOutReg1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numLgScOutReg1 <= 8'b00000110;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numLgScOutReg1 <= tmp_54;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numLgScOutReg2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numLgScOutReg2 <= 8'b00000110;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numLgScOutReg2 <= obj_symbolFormationObj_numLgScOutReg1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numLgScOutReg3_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numLgScOutReg3 <= 8'b00000110;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numLgScOutReg3 <= obj_symbolFormationObj_numLgScOutReg2;
        end
      end
    end



  assign tmp_55 = obj_symbolFormationObj_outCountReg2 < obj_symbolFormationObj_numLgScOutReg3;



  assign tmp_56 = obj_symbolFormationObj_outCount_1 == 8'b00000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp512
  assign tmp_57 = obj_symbolFormationObj_numDataSc + obj_symbolFormationObj_numLgScSampled;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numDataScPlusNumLgScReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numDataScPlusNumLgScReg <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numDataScPlusNumLgScReg <= tmp_58;
        end
      end
    end



  assign tmp_58 = (tmp_56 == 1'b0 ? obj_symbolFormationObj_numDataScPlusNumLgScReg :
              tmp_57);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numDataScPlusNumLgScReg1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numDataScPlusNumLgScReg1 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numDataScPlusNumLgScReg1 <= tmp_58;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numDataScPlusNumLgScReg2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numDataScPlusNumLgScReg2 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numDataScPlusNumLgScReg2 <= obj_symbolFormationObj_numDataScPlusNumLgScReg1;
        end
      end
    end



  assign tmp_59 = obj_symbolFormationObj_outCountReg1 < obj_symbolFormationObj_numDataScPlusNumLgScReg2;



  assign tmp_60 = obj_symbolFormationObj_outCount_1 == 8'b00000000;



  assign tmp_61 = obj_symbolFormationObj_inCount_1 == 8'b00000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp140
  assign tmp_62 = (tmp_61 == 1'b0 ? obj_symbolFormationObj_FFTSampled :
              obj_symbolFormationObj_FFTLenReg);



  assign tmp_63 = (obj_symbolFormationObj_validInReg == 1'b0 ? obj_symbolFormationObj_FFTSampled :
              tmp_62);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTSampled_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTSampled <= 8'b01000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTSampled <= tmp_63;
        end
      end
    end



  assign tmp_64 = obj_symbolFormationObj_inCount_1 == 8'b00000000;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numRgScRegDelay2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numRgScRegDelay2_1 <= 8'b00000101;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numRgScRegDelay2_1 <= obj_symbolFormationObj_numRgScRegDelay2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numRgScRegDelay1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numRgScRegDelay1 <= 8'b00000101;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numRgScRegDelay1 <= obj_symbolFormationObj_numRgScRegDelay2_1;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp624
  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numRgScReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numRgScReg <= 8'b00000101;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numRgScReg <= obj_symbolFormationObj_numRgScRegDelay1;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp152
  assign tmp_65 = (tmp_64 == 1'b0 ? obj_symbolFormationObj_numRgScSampled :
              obj_symbolFormationObj_numRgScReg);



  assign tmp_66 = (obj_symbolFormationObj_validInReg == 1'b0 ? obj_symbolFormationObj_numRgScSampled :
              tmp_65);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numRgScSampled_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numRgScSampled <= 8'b00000101;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numRgScSampled <= tmp_66;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp516
  assign tmp_67 = obj_symbolFormationObj_FFTSampled - obj_symbolFormationObj_numRgScSampled;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenMinusNumRgScReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenMinusNumRgScReg <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenMinusNumRgScReg <= tmp_68;
        end
      end
    end



  assign tmp_68 = (tmp_60 == 1'b0 ? obj_symbolFormationObj_FFTLenMinusNumRgScReg :
              tmp_67);



  assign tmp_69 = obj_symbolFormationObj_outCount_1 < tmp_54;



  assign tmp_70 = obj_symbolFormationObj_outCount_1 == 8'b00000000;



  assign tmp_71 = obj_symbolFormationObj_outCount_1 < tmp_54;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp453
  assign obj_symbolFormationObj_numLgScCountReg = 8'b00000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp441
  assign obj_symbolFormationObj_numLgScCountReg_1 = 8'b00000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp508
  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numLgScCount_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numLgScCount <= 8'b00000110;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numLgScCount <= obj_symbolFormationObj_numLgScSampled;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp453
  assign tmp_73 = tmp_72 - 8'b00000001;



  assign tmp_74 = tmp_72 == 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp441
  assign tmp_75 = (tmp_74 == 1'b0 ? tmp_73 :
              obj_symbolFormationObj_numLgScCountReg);



  assign tmp_76 = tmp_72 < 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp241
  assign tmp_77 = (tmp_76 == 1'b0 ? tmp_75 :
              obj_symbolFormationObj_numLgScCountReg_1);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp220
  assign tmp_78 = (tmp_71 == 1'b0 ? tmp_72 :
              tmp_77);



  assign tmp_79 = (obj_symbolFormationObj_startSymbForm_2 == 1'b0 ? tmp_72 :
              tmp_78);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numLgScCountReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numLgScCountReg_2 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numLgScCountReg_2 <= tmp_79;
        end
      end
    end



  assign tmp_72 = (tmp_70 == 1'b0 ? obj_symbolFormationObj_numLgScCountReg_2 :
              obj_symbolFormationObj_numLgScCount);



  assign tmp_80 = tmp_72 == 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp449
  assign obj_symbolFormationObj_numSampLeft = 8'b00000000;



  assign tmp_81 = tmp_72 < 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp449
  assign obj_symbolFormationObj_numSampLeft_1 = 8'b00000000;



  assign tmp_82 = (tmp_80 == 1'b0 ? obj_symbolFormationObj_numSampLeft :
              obj_symbolFormationObj_numSampLeft_1);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_insertDC_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_insertDC_1 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_insertDC_1 <= obj_symbolFormationObj_insertDC;
        end
      end
    end



  assign tmp_83 = obj_symbolFormationObj_insertDC_1 != 8'b00000000;



  assign tmp_84 = tmp_72 + 8'b00000001;



  assign tmp_85 = (tmp_83 == 1'b0 ? tmp_72 :
              tmp_84);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp238
  assign tmp_86 = (tmp_81 == 1'b0 ? tmp_82 :
              tmp_85);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp216
  assign tmp_87 = (tmp_69 == 1'b0 ? obj_symbolFormationObj_numSampLeft_2 :
              tmp_86);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numSampLeft_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numSampLeft_2 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numSampLeft_2 <= tmp_88;
        end
      end
    end



  assign tmp_88 = (obj_symbolFormationObj_startSymbForm_2 == 1'b0 ? obj_symbolFormationObj_numSampLeft_2 :
              tmp_87);



  assign tmp_89 = tmp_68 - tmp_88;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_maxLimitForDataReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_maxLimitForDataReg <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_maxLimitForDataReg <= tmp_89;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_maxLimitForDataReg1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_maxLimitForDataReg1 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_maxLimitForDataReg1 <= obj_symbolFormationObj_maxLimitForDataReg;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_maxLimitForDataReg2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_maxLimitForDataReg2 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_maxLimitForDataReg2 <= obj_symbolFormationObj_maxLimitForDataReg1;
        end
      end
    end



  assign tmp_90 = obj_symbolFormationObj_outCountReg1 < obj_symbolFormationObj_maxLimitForDataReg2;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp588
  assign out_4 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp267
  assign out_5 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp588
  assign out_6 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp267
  assign tmp_91 = (tmp_90 == 1'b0 ? out_4 :
              out_6);



  assign tmp_92 = (tmp_59 == 1'b0 ? out_5 :
              tmp_91);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_enbDataPlacing_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_enbDataPlacing <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_enbDataPlacing <= tmp_92;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp383
  assign obj_symbolFormationObj_sendDC = 1'b0;



  assign tmp_93 = obj_symbolFormationObj_outCount_1 == 8'b00000000;



  assign tmp_94 = obj_symbolFormationObj_FFTSampled >>> 8'd1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp520
  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenBy2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenBy2 <= 8'b00100000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenBy2 <= tmp_94;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenBy2Reg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenBy2Reg <= 8'b00100000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenBy2Reg <= tmp_95;
        end
      end
    end



  assign tmp_95 = (tmp_93 == 1'b0 ? obj_symbolFormationObj_FFTLenBy2Reg :
              obj_symbolFormationObj_FFTLenBy2);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenBy2Reg1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenBy2Reg1 <= 8'b00100000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenBy2Reg1 <= tmp_95;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenBy2Reg2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenBy2Reg2 <= 8'b00100000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenBy2Reg2 <= obj_symbolFormationObj_FFTLenBy2Reg1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenBy2Reg3_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenBy2Reg3 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenBy2Reg3 <= obj_symbolFormationObj_FFTLenBy2Reg2;
        end
      end
    end



  assign tmp_96 = (obj_symbolFormationObj_outCountReg2 == obj_symbolFormationObj_FFTLenBy2Reg3) && (obj_symbolFormationObj_insertDC_1 != 8'b00000000);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp407
  assign obj_symbolFormationObj_sendDC_1 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp407
  assign obj_symbolFormationObj_sendDC_2 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp383
  assign tmp_97 = (tmp_96 == 1'b0 ? obj_symbolFormationObj_sendDC_1 :
              obj_symbolFormationObj_sendDC_2);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp353
  assign tmp_98 = (obj_symbolFormationObj_enbDataPlacing == 1'b0 ? obj_symbolFormationObj_sendDC :
              tmp_97);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp353
  assign obj_symbolFormationObj_sendDC_3 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp300
  assign tmp_99 = (tmp_55 == 1'b0 ? tmp_98 :
              obj_symbolFormationObj_sendDC_3);



  assign tmp_100 = (obj_symbolFormationObj_startSymbFormReg2 == 1'b0 ? obj_symbolFormationObj_sendDC_4 :
              tmp_99);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_sendDC_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_sendDC_4 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_sendDC_4 <= tmp_100;
        end
      end
    end



  assign tmp_101 = obj_symbolFormationObj_outCountReg2 < obj_symbolFormationObj_numLgScOutReg3;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenMinusVecLenReg1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenMinusVecLenReg1 <= 8'b01000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenMinusVecLenReg1 <= tmp_34;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenMinusVecLenReg2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenMinusVecLenReg2 <= 8'b01000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenMinusVecLenReg2 <= obj_symbolFormationObj_FFTLenMinusVecLenReg1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_FFTLenMinusVecLenReg3_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_FFTLenMinusVecLenReg3 <= 8'b01000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_FFTLenMinusVecLenReg3 <= obj_symbolFormationObj_FFTLenMinusVecLenReg2;
        end
      end
    end



  assign tmp_102 = obj_symbolFormationObj_outCountReg2 < obj_symbolFormationObj_numLgScOutReg3;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp379
  assign obj_symbolFormationObj_prevVecSamples = 8'b00000000;



  assign tmp_103 = (obj_symbolFormationObj_outCountReg2 == obj_symbolFormationObj_FFTLenBy2Reg3) && (obj_symbolFormationObj_insertDC_1 != 8'b00000000);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp404
  assign obj_symbolFormationObj_prevVecSamples_1 = 8'b00000001;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numLgScCountReg1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numLgScCountReg1 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numLgScCountReg1 <= tmp_72;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numLgScCountReg2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numLgScCountReg2 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numLgScCountReg2 <= obj_symbolFormationObj_numLgScCountReg1;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp435
  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numLgScCountReg3_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numLgScCountReg3 <= 8'b00000110;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numLgScCountReg3 <= obj_symbolFormationObj_numLgScCountReg2;
        end
      end
    end



  assign tmp_104 = obj_symbolFormationObj_numLgScCountReg3 < 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp435
  assign obj_symbolFormationObj_prevVecSamples_2 = 8'b00000000;



  assign tmp_105 = obj_symbolFormationObj_outCountReg2 == obj_symbolFormationObj_FFTLenMinusVecLenReg3;



  assign tmp_106 = (tmp_104 == 1'b0 ? obj_symbolFormationObj_prevVecSamples_2 :
              obj_symbolFormationObj_numLgScCountReg3);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp334
  assign obj_symbolFormationObj_prevVecSamples_3 = 8'b00000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp379
  assign tmp_107 = (tmp_103 == 1'b0 ? obj_symbolFormationObj_prevVecSamples_4 :
              obj_symbolFormationObj_prevVecSamples_1);



  assign tmp_108 = (obj_symbolFormationObj_enbDataPlacing == 1'b0 ? obj_symbolFormationObj_prevVecSamples :
              tmp_107);



  assign tmp_109 = (tmp_102 == 1'b0 ? tmp_108 :
              tmp_106);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp304
  assign tmp_110 = (tmp_105 == 1'b0 ? tmp_109 :
              obj_symbolFormationObj_prevVecSamples_3);



  assign tmp_111 = (obj_symbolFormationObj_startSymbFormReg2 == 1'b0 ? obj_symbolFormationObj_prevVecSamples_4 :
              tmp_110);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_prevVecSamples_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_prevVecSamples_4 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_prevVecSamples_4 <= tmp_111;
        end
      end
    end



  assign tmp_112 = (obj_symbolFormationObj_enbDataPlacing == 1'b0 ? obj_symbolFormationObj_prevVecSamples_4 :
              obj_symbolFormationObj_prevVecSamples_4);



  assign tmp_113 = obj_symbolFormationObj_numLgScCountReg3 == 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp569
  assign obj_symbolFormationObj_dataVec1Samples = 8'b00000000;



  assign tmp_114 = obj_symbolFormationObj_numLgScCountReg3 < 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp569
  assign obj_symbolFormationObj_dataVec1Samples_1 = 8'b00000000;



  assign tmp_115 = (tmp_113 == 1'b0 ? obj_symbolFormationObj_dataVec1Samples :
              obj_symbolFormationObj_dataVec1Samples_1);



  assign tmp_116 = (tmp_114 == 1'b0 ? tmp_115 :
              obj_symbolFormationObj_numLgScCountReg3);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp276
  assign tmp_117 = (tmp_101 == 1'b0 ? tmp_112 :
              tmp_116);



  assign tmp_118 = (obj_symbolFormationObj_startSymbFormReg2 == 1'b0 ? obj_symbolFormationObj_dataVec1Samples_2 :
              tmp_117);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_dataVec1Samples_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_dataVec1Samples_2 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_dataVec1Samples_2 <= tmp_118;
        end
      end
    end



  assign tmp_119 = obj_symbolFormationObj_dataVec1Samples_2 > 8'b00000000;



  assign tmp_120 = obj_symbolFormationObj_outCountReg2 < obj_symbolFormationObj_numLgScOutReg3;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp363
  assign obj_symbolFormationObj_dataVec2_re = 16'sb0000000000000000;
  assign obj_symbolFormationObj_dataVec2_im = 16'sb0000000000000000;



  assign tmp_121 = obj_symbolFormationObj_outCount_1 < tmp_58;



  assign tmp_122 = obj_symbolFormationObj_outCount_1 < obj_symbolFormationObj_maxLimitForDataReg;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp595
  assign out_7 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp251
  assign out_8 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp595
  assign out_9 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp251
  assign tmp_123 = (tmp_122 == 1'b0 ? out_7 :
              out_9);



  assign tmp_124 = (tmp_121 == 1'b0 ? out_8 :
              tmp_123);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp246
  assign obj_symbolFormationObj_startRead = 1'b0;



  assign tmp_125 = tmp_72 == 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp457
  assign obj_symbolFormationObj_startRead_1 = 1'b0;



  assign tmp_126 = tmp_72 < 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp457
  assign obj_symbolFormationObj_startRead_2 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp445
  assign tmp_127 = (tmp_125 == 1'b0 ? obj_symbolFormationObj_startRead_1 :
              obj_symbolFormationObj_startRead_2);



  assign tmp_128 = obj_symbolFormationObj_outCount_1 < tmp_54;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp246
  assign obj_symbolFormationObj_startRead_3 = 1'b1;



  assign tmp_129 = (tmp_124 == 1'b0 ? obj_symbolFormationObj_startRead :
              obj_symbolFormationObj_startRead_3);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp445
  assign obj_symbolFormationObj_startRead_4 = 1'b1;



  assign tmp_130 = (tmp_126 == 1'b0 ? tmp_127 :
              obj_symbolFormationObj_startRead_4);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp224
  assign tmp_131 = (tmp_128 == 1'b0 ? tmp_129 :
              tmp_130);



  assign tmp_132 = (obj_symbolFormationObj_startSymbForm_2 == 1'b0 ? obj_symbolFormationObj_startRead_5 :
              tmp_131);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_startRead_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_startRead_5 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_startRead_5 <= tmp_132;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_startReadFromRAM_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_startReadFromRAM <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_startReadFromRAM <= obj_symbolFormationObj_startRead_5;
        end
      end
    end



  assign tmp_133 = obj_symbolFormationObj_outCount_1 == 8'b00000000;



  assign tmp_134 = obj_symbolFormationObj_inCount_1 == 8'b00000000;



  assign obj_symbolFormationObj_CPLenRegDelay2 = 8'b00100000;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_CPLenRegDelay2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_CPLenRegDelay2_1 <= 8'b00010000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_CPLenRegDelay2_1 <= obj_symbolFormationObj_CPLenRegDelay2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_CPLenRegDelay1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_CPLenRegDelay1 <= 8'b00010000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_CPLenRegDelay1 <= obj_symbolFormationObj_CPLenRegDelay2_1;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp618
  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_CPLenReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_CPLenReg <= 8'b00010000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_CPLenReg <= obj_symbolFormationObj_CPLenRegDelay1;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp144
  assign tmp_135 = (tmp_134 == 1'b0 ? obj_symbolFormationObj_CPSampled :
              obj_symbolFormationObj_CPLenReg);



  assign tmp_136 = (obj_symbolFormationObj_validInReg == 1'b0 ? obj_symbolFormationObj_CPSampled :
              tmp_135);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp496
  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_CPSampled_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_CPSampled <= 8'b00010000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_CPSampled <= tmp_136;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_CPSampledReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_CPSampledReg <= 8'b00010000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_CPSampledReg <= tmp_137;
        end
      end
    end



  assign tmp_137 = (tmp_133 == 1'b0 ? obj_symbolFormationObj_CPSampledReg :
              obj_symbolFormationObj_CPSampled);



  assign tmp_138 = tmp_137 == 8'b00000000;



  assign tmp_139 = obj_symbolFormationObj_outCount_1 == tmp_34;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp465
  assign tmp_140 =  ! obj_symbolFormationObj_selectRAM;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp228
  assign tmp_141 = (tmp_139 == 1'b0 ? obj_symbolFormationObj_selectRAM :
              tmp_140);



  assign tmp_142 = (obj_symbolFormationObj_startSymbForm_2 == 1'b0 ? obj_symbolFormationObj_selectRAM :
              tmp_141);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_selectRAM_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_selectRAM <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_selectRAM <= tmp_142;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_selectRAMReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_selectRAMReg <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_selectRAMReg <= obj_symbolFormationObj_selectRAM;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_selectRAMReg1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_selectRAMReg1 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_selectRAMReg1 <= obj_symbolFormationObj_selectRAMReg;
        end
      end
    end



  assign tmp_143 = (tmp_138 == 1'b0 ? obj_symbolFormationObj_selectRAMReg1 :
              obj_symbolFormationObj_selectRAMReg);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_RAM2ReadSelect_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_RAM2ReadSelect <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_RAM2ReadSelect <= tmp_143;
        end
      end
    end



  assign tmp_144 =  ! obj_symbolFormationObj_RAM2ReadSelect;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_dataInRegDelay2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_dataInRegDelay2_re <= 16'sb0000000000000000;
        obj_symbolFormationObj_dataInRegDelay2_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_dataInRegDelay2_re <= tmp_re;
          obj_symbolFormationObj_dataInRegDelay2_im <= tmp_im;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_dataInRegDelay1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_dataInRegDelay1_re <= 16'sb0000000000000000;
        obj_symbolFormationObj_dataInRegDelay1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_dataInRegDelay1_re <= obj_symbolFormationObj_dataInRegDelay2_re;
          obj_symbolFormationObj_dataInRegDelay1_im <= obj_symbolFormationObj_dataInRegDelay2_im;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_dataInReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_dataInReg_re <= 16'sb0000000000000000;
        obj_symbolFormationObj_dataInReg_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_dataInReg_re <= obj_symbolFormationObj_dataInRegDelay1_re;
          obj_symbolFormationObj_dataInReg_im <= obj_symbolFormationObj_dataInRegDelay1_im;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_dataInReg1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_dataInReg1_re <= 16'sb0000000000000000;
        obj_symbolFormationObj_dataInReg1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_dataInReg1_re <= obj_symbolFormationObj_dataInReg_re;
          obj_symbolFormationObj_dataInReg1_im <= obj_symbolFormationObj_dataInReg_im;
        end
      end
    end



  assign tmp_145 = obj_symbolFormationObj_inCountReg >= obj_symbolFormationObj_numDataScMinusVecLen;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp199
  assign obj_symbolFormationObj_writeAddrRAM2 = 9'b000000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp199
  assign tmp_146 = obj_symbolFormationObj_writeAddrRAM2_1 + 9'b000000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp193
  assign tmp_147 = (tmp_145 == 1'b0 ? tmp_146 :
              obj_symbolFormationObj_writeAddrRAM2);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp172
  assign tmp_148 = (obj_symbolFormationObj_writeEnbRAM2 == 1'b0 ? obj_symbolFormationObj_writeAddrRAM2_1 :
              tmp_147);



  assign tmp_149 = (obj_symbolFormationObj_writeEnbRAM1 == 1'b0 ? tmp_148 :
              obj_symbolFormationObj_writeAddrRAM2_1);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_writeAddrRAM2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_writeAddrRAM2_1 <= 9'b000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_writeAddrRAM2_1 <= tmp_149;
        end
      end
    end



  assign tmp_150 = obj_symbolFormationObj_startRead_5 && obj_symbolFormationObj_startSymbFormReg;



  assign tmp_151 = obj_symbolFormationObj_startRead_5 && obj_symbolFormationObj_startSymbFormReg;



  assign tmp_152 = obj_symbolFormationObj_outCount_1 == 8'b00000000;



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_numDataScMinusVecLenReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_numDataScMinusVecLenReg <= 8'b01000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_numDataScMinusVecLenReg <= tmp_153;
        end
      end
    end



  assign tmp_153 = (tmp_152 == 1'b0 ? obj_symbolFormationObj_numDataScMinusVecLenReg :
              obj_symbolFormationObj_numDataScMinusVecLen);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp479
  assign obj_symbolFormationObj_readCount = 8'b00000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp479
  assign tmp_154 = obj_symbolFormationObj_readCount_1 + 8'b00000001;



  assign tmp_155 = obj_symbolFormationObj_readCount_1 >= tmp_153;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp260
  assign tmp_156 = (tmp_155 == 1'b0 ? tmp_154 :
              obj_symbolFormationObj_readCount);



  assign tmp_157 = (tmp_151 == 1'b0 ? obj_symbolFormationObj_readCount_1 :
              tmp_156);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_readCount_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_readCount_1 <= 8'b00000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_readCount_1 <= tmp_157;
        end
      end
    end



  assign tmp_158 = obj_symbolFormationObj_readCount_1 >= tmp_153;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp475
  assign obj_symbolFormationObj_readAddr = 9'b000000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp475
  assign tmp_159 = obj_symbolFormationObj_readAddr_1 + 9'b000000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp256
  assign tmp_160 = (tmp_158 == 1'b0 ? tmp_159 :
              obj_symbolFormationObj_readAddr);



  assign tmp_161 = (tmp_150 == 1'b0 ? obj_symbolFormationObj_readAddr_1 :
              tmp_160);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_readAddr_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_readAddr_1 <= 9'b000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_readAddr_1 <= tmp_161;
        end
      end
    end



  whdlOFDMTx_SimpleDualPortRAM_generic #(.AddrWidth(9),
                                         .DataWidth(16)
                                         )
                                       u_simpleDualPortRam (.clk(clk),
                                                            .enb_1_32_0(enb_1_32_0),
                                                            .wr_din_re(obj_symbolFormationObj_dataInReg1_re),
                                                            .wr_din_im(obj_symbolFormationObj_dataInReg1_im),
                                                            .wr_addr(obj_symbolFormationObj_writeAddrRAM2_1),
                                                            .wr_en(obj_symbolFormationObj_writeEnbRAM2),
                                                            .rd_addr(obj_symbolFormationObj_readAddr_1),
                                                            .rd_dout_re(tmp_re_1),
                                                            .rd_dout_im(tmp_im_1)
                                                            );

  assign tmp_162 = obj_symbolFormationObj_inCountReg >= obj_symbolFormationObj_numDataScMinusVecLen;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp186
  assign obj_symbolFormationObj_writeAddrRAM1 = 9'b000000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp186
  assign tmp_163 = obj_symbolFormationObj_writeAddrRAM1_1 + 9'b000000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp180
  assign tmp_164 = (tmp_162 == 1'b0 ? tmp_163 :
              obj_symbolFormationObj_writeAddrRAM1);



  assign tmp_165 = (obj_symbolFormationObj_writeEnbRAM1 == 1'b0 ? obj_symbolFormationObj_writeAddrRAM1_1 :
              tmp_164);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_writeAddrRAM1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_writeAddrRAM1_1 <= 9'b000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_writeAddrRAM1_1 <= tmp_165;
        end
      end
    end



  whdlOFDMTx_SimpleDualPortRAM_generic #(.AddrWidth(9),
                                         .DataWidth(16)
                                         )
                                       u_simpleDualPortRam_1 (.clk(clk),
                                                              .enb_1_32_0(enb_1_32_0),
                                                              .wr_din_re(obj_symbolFormationObj_dataInReg1_re),
                                                              .wr_din_im(obj_symbolFormationObj_dataInReg1_im),
                                                              .wr_addr(obj_symbolFormationObj_writeAddrRAM1_1),
                                                              .wr_en(obj_symbolFormationObj_writeEnbRAM1),
                                                              .rd_addr(obj_symbolFormationObj_readAddr_1),
                                                              .rd_dout_re(tmp_re_2),
                                                              .rd_dout_im(tmp_im_2)
                                                              );

  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp331
  assign tmp_re_3 = (tmp_144 == 1'b0 ? tmp_re_1 :
              tmp_re_2);
  assign tmp_im_3 = (tmp_144 == 1'b0 ? tmp_im_1 :
              tmp_im_2);



  assign tmp_re_4 = (obj_symbolFormationObj_startReadFromRAM == 1'b0 ? obj_symbolFormationObj_dataOutRAM_re :
              tmp_re_3);
  assign tmp_im_4 = (obj_symbolFormationObj_startReadFromRAM == 1'b0 ? obj_symbolFormationObj_dataOutRAM_im :
              tmp_im_3);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp363
  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp375
  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp431
  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_dataOutRAM_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_dataOutRAM_re <= 16'sb0000000000000000;
        obj_symbolFormationObj_dataOutRAM_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_dataOutRAM_re <= tmp_re_4;
          obj_symbolFormationObj_dataOutRAM_im <= tmp_im_4;
        end
      end
    end



  assign tmp_re_5 = (obj_symbolFormationObj_enbDataPlacing == 1'b0 ? obj_symbolFormationObj_dataVec2_re :
              obj_symbolFormationObj_dataOutRAM_re);
  assign tmp_im_5 = (obj_symbolFormationObj_enbDataPlacing == 1'b0 ? obj_symbolFormationObj_dataVec2_im :
              obj_symbolFormationObj_dataOutRAM_im);



  assign tmp_166 = obj_symbolFormationObj_numLgScCountReg3 < 8'b00000001;



  assign tmp_167 = obj_symbolFormationObj_numLgScCountReg3 == 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp577
  assign obj_symbolFormationObj_dataVec2_re_1 = 16'sb0000000000000000;
  assign obj_symbolFormationObj_dataVec2_im_1 = 16'sb0000000000000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp577
  assign obj_symbolFormationObj_dataVec2_re_2 = 16'sb0000000000000000;
  assign obj_symbolFormationObj_dataVec2_im_2 = 16'sb0000000000000000;



  assign tmp_re_6 = (tmp_167 == 1'b0 ? obj_symbolFormationObj_dataVec2_re_1 :
              obj_symbolFormationObj_dataVec2_re_2);
  assign tmp_im_6 = (tmp_167 == 1'b0 ? obj_symbolFormationObj_dataVec2_im_1 :
              obj_symbolFormationObj_dataVec2_im_2);



  assign tmp_re_7 = (tmp_166 == 1'b0 ? tmp_re_6 :
              obj_symbolFormationObj_dataOutRAM_re);
  assign tmp_im_7 = (tmp_166 == 1'b0 ? tmp_im_6 :
              obj_symbolFormationObj_dataOutRAM_im);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp284
  assign tmp_re_8 = (tmp_120 == 1'b0 ? tmp_re_5 :
              tmp_re_7);
  assign tmp_im_8 = (tmp_120 == 1'b0 ? tmp_im_5 :
              tmp_im_7);



  assign tmp_re_9 = (obj_symbolFormationObj_startSymbFormReg2 == 1'b0 ? obj_symbolFormationObj_dataVec2_re_3 :
              tmp_re_8);
  assign tmp_im_9 = (obj_symbolFormationObj_startSymbFormReg2 == 1'b0 ? obj_symbolFormationObj_dataVec2_im_3 :
              tmp_im_8);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_dataVec2_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_dataVec2_re_3 <= 16'sb0000000000000000;
        obj_symbolFormationObj_dataVec2_im_3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_dataVec2_re_3 <= tmp_re_9;
          obj_symbolFormationObj_dataVec2_im_3 <= tmp_im_9;
        end
      end
    end



  assign tmp_168 = obj_symbolFormationObj_outCountReg2 < obj_symbolFormationObj_numLgScOutReg3;



  assign tmp_169 = obj_symbolFormationObj_outCountReg2 < obj_symbolFormationObj_numLgScOutReg3;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp375
  assign obj_symbolFormationObj_prevVecData_re = 16'sb0000000000000000;
  assign obj_symbolFormationObj_prevVecData_im = 16'sb0000000000000000;



  assign tmp_re_10 = (obj_symbolFormationObj_enbDataPlacing == 1'b0 ? obj_symbolFormationObj_prevVecData_re :
              obj_symbolFormationObj_dataOutRAM_re);
  assign tmp_im_10 = (obj_symbolFormationObj_enbDataPlacing == 1'b0 ? obj_symbolFormationObj_prevVecData_im :
              obj_symbolFormationObj_dataOutRAM_im);



  assign tmp_170 = obj_symbolFormationObj_numLgScCountReg3 < 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp431
  assign obj_symbolFormationObj_prevVecData_re_1 = 16'sb0000000000000000;
  assign obj_symbolFormationObj_prevVecData_im_1 = 16'sb0000000000000000;



  assign tmp_re_11 = (tmp_170 == 1'b0 ? obj_symbolFormationObj_prevVecData_re_1 :
              obj_symbolFormationObj_dataOutRAM_re);
  assign tmp_im_11 = (tmp_170 == 1'b0 ? obj_symbolFormationObj_prevVecData_im_1 :
              obj_symbolFormationObj_dataOutRAM_im);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp296
  assign tmp_re_12 = (tmp_169 == 1'b0 ? tmp_re_10 :
              tmp_re_11);
  assign tmp_im_12 = (tmp_169 == 1'b0 ? tmp_im_10 :
              tmp_im_11);



  assign tmp_re_13 = (obj_symbolFormationObj_startSymbFormReg2 == 1'b0 ? obj_symbolFormationObj_prevVecData_re_2 :
              tmp_re_12);
  assign tmp_im_13 = (obj_symbolFormationObj_startSymbFormReg2 == 1'b0 ? obj_symbolFormationObj_prevVecData_im_2 :
              tmp_im_12);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_prevVecData_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_prevVecData_re_2 <= 16'sb0000000000000000;
        obj_symbolFormationObj_prevVecData_im_2 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_prevVecData_re_2 <= tmp_re_13;
          obj_symbolFormationObj_prevVecData_im_2 <= tmp_im_13;
        end
      end
    end



  assign tmp_re_14 = (obj_symbolFormationObj_enbDataPlacing == 1'b0 ? obj_symbolFormationObj_prevVecData_re_2 :
              obj_symbolFormationObj_prevVecData_re_2);
  assign tmp_im_14 = (obj_symbolFormationObj_enbDataPlacing == 1'b0 ? obj_symbolFormationObj_prevVecData_im_2 :
              obj_symbolFormationObj_prevVecData_im_2);



  assign tmp_171 = obj_symbolFormationObj_numLgScCountReg3 < 8'b00000001;



  assign tmp_172 = obj_symbolFormationObj_numLgScCountReg3 == 8'b00000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp565
  assign obj_symbolFormationObj_dataVec1_re = 16'sb0000000000000000;
  assign obj_symbolFormationObj_dataVec1_im = 16'sb0000000000000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp565
  assign obj_symbolFormationObj_dataVec1_re_1 = 16'sb0000000000000000;
  assign obj_symbolFormationObj_dataVec1_im_1 = 16'sb0000000000000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp411
  assign tmp_re_15 = (tmp_172 == 1'b0 ? obj_symbolFormationObj_dataVec1_re :
              obj_symbolFormationObj_dataVec1_re_1);
  assign tmp_im_15 = (tmp_172 == 1'b0 ? obj_symbolFormationObj_dataVec1_im :
              obj_symbolFormationObj_dataVec1_im_1);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp411
  assign obj_symbolFormationObj_dataVec1_re_2 = 16'sb0000000000000000;
  assign obj_symbolFormationObj_dataVec1_im_2 = 16'sb0000000000000000;



  assign tmp_re_16 = (tmp_171 == 1'b0 ? tmp_re_15 :
              obj_symbolFormationObj_dataVec1_re_2);
  assign tmp_im_16 = (tmp_171 == 1'b0 ? tmp_im_15 :
              obj_symbolFormationObj_dataVec1_im_2);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp272
  assign tmp_re_17 = (tmp_168 == 1'b0 ? tmp_re_14 :
              tmp_re_16);
  assign tmp_im_17 = (tmp_168 == 1'b0 ? tmp_im_14 :
              tmp_im_16);



  assign tmp_re_18 = (obj_symbolFormationObj_startSymbFormReg2 == 1'b0 ? obj_symbolFormationObj_dataVec1_re_3 :
              tmp_re_17);
  assign tmp_im_18 = (obj_symbolFormationObj_startSymbFormReg2 == 1'b0 ? obj_symbolFormationObj_dataVec1_im_3 :
              tmp_im_17);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_dataVec1_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_dataVec1_re_3 <= 16'sb0000000000000000;
        obj_symbolFormationObj_dataVec1_im_3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_dataVec1_re_3 <= tmp_re_18;
          obj_symbolFormationObj_dataVec1_im_3 <= tmp_im_18;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp547
  assign tmp_re_19 = (tmp_119 == 1'b0 ? obj_symbolFormationObj_dataVec2_re_3 :
              obj_symbolFormationObj_dataVec1_re_3);
  assign tmp_im_19 = (tmp_119 == 1'b0 ? obj_symbolFormationObj_dataVec2_im_3 :
              obj_symbolFormationObj_dataVec1_im_3);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp547
  assign obj_symbolFormationObj_dataOutReg_re_1 = 16'sb0000000000000000;
  assign obj_symbolFormationObj_dataOutReg_im_1 = 16'sb0000000000000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp313
  assign tmp_re_20 = (obj_symbolFormationObj_sendDC_4 == 1'b0 ? tmp_re_19 :
              obj_symbolFormationObj_dataOutReg_re_1);
  assign tmp_im_20 = (obj_symbolFormationObj_sendDC_4 == 1'b0 ? tmp_im_19 :
              obj_symbolFormationObj_dataOutReg_im_1);



  assign tmp_re_21 = (obj_symbolFormationObj_sendOutput_2 == 1'b0 ? obj_symbolFormationObj_dataOutReg_re :
              tmp_re_20);
  assign tmp_im_21 = (obj_symbolFormationObj_sendOutput_2 == 1'b0 ? obj_symbolFormationObj_dataOutReg_im :
              tmp_im_20);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_dataOutReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_dataOutReg_re_2 <= 16'sb0000000000000000;
        obj_symbolFormationObj_dataOutReg_im_2 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_dataOutReg_re_2 <= tmp_re_21;
          obj_symbolFormationObj_dataOutReg_im_2 <= tmp_im_21;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_dataOut_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_dataOut_re <= 16'sb0000000000000000;
        obj_symbolFormationObj_dataOut_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_dataOut_re <= obj_symbolFormationObj_dataOutReg_re_2;
          obj_symbolFormationObj_dataOut_im <= obj_symbolFormationObj_dataOutReg_im_2;
        end
      end
    end



  assign varargout_1_re = obj_symbolFormationObj_dataOut_re;

  assign varargout_1_im = obj_symbolFormationObj_dataOut_im;

  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp326
  assign obj_symbolFormationObj_validOutReg = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp326
  assign obj_symbolFormationObj_validOutReg_1 = 1'b1;



  assign tmp_173 = (obj_symbolFormationObj_sendOutput_2 == 1'b0 ? obj_symbolFormationObj_validOutReg :
              obj_symbolFormationObj_validOutReg_1);



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_validOutReg_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_validOutReg_2 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_validOutReg_2 <= tmp_173;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : obj_symbolFormationObj_validOut_reg_process
      if (reset == 1'b1) begin
        obj_symbolFormationObj_validOut <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          obj_symbolFormationObj_validOut <= obj_symbolFormationObj_validOutReg_2;
        end
      end
    end



  assign varargout_2 = obj_symbolFormationObj_validOut;

endmodule  // whdlOFDMTx_symbolFormation

