// -------------------------------------------------------------
// 
// File Name: D:\NU\OF\WHDLOFDMTransmitterExample_all_new\hdl_prj\hdlsrc3\whdlOFDMTransmitter_up_con\whdlOFDMTx\whdlOFDMTx_RADIX22FFT_SDF2_2.v
// Created: 2023-05-02 12:36:36
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: whdlOFDMTx_RADIX22FFT_SDF2_2
// Source Path: dsphdl.IFFT/RADIX22FFT_SDF2_2
// Hierarchy Level: 5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module whdlOFDMTx_RADIX22FFT_SDF2_2
          (clk,
           reset,
           enb_1_32_0,
           dout_1_1_re,
           dout_1_1_im,
           dout_1_1_vld,
           rd_2_Addr,
           rd_2_Enb,
           proc_2_enb,
           multiply_2_J,
           dout_2_1_re,
           dout_2_1_im,
           dout_2_1_vld,
           dinXTwdl_2_1_vld);


  input   clk;
  input   reset;
  input   enb_1_32_0;
  input   signed [15:0] dout_1_1_re;  // sfix16_En14
  input   signed [15:0] dout_1_1_im;  // sfix16_En14
  input   dout_1_1_vld;
  input   [4:0] rd_2_Addr;  // ufix5
  input   rd_2_Enb;
  input   proc_2_enb;
  input   multiply_2_J;
  output  signed [15:0] dout_2_1_re;  // sfix16_En14
  output  signed [15:0] dout_2_1_im;  // sfix16_En14
  output  dout_2_1_vld;
  output  dinXTwdl_2_1_vld;


  wire btfin_vld;
  wire saveEnb;
  wire dinVld;
  reg  x_vld;
  reg  x_vld_dly;
  wire signed [15:0] wrData_im;  // sfix16_En14
  wire [4:0] wrAddr;  // ufix5
  wire wrEnb;
  wire signed [15:0] x_im;  // sfix16_En14
  reg signed [15:0] x_im_dly;  // sfix16_En14
  wire signed [15:0] wrData_re;  // sfix16_En14
  wire signed [15:0] x_re;  // sfix16_En14
  reg signed [15:0] x_re_dly;  // sfix16_En14
  reg  Radix22ButterflyG2_procEnb_dly;
  reg  Radix22ButterflyG2_procEnb_dly1;
  reg  Radix22ButterflyG2_procEnb_dly2;
  reg signed [16:0] Radix22ButterflyG2_btf1_re_reg;  // sfix17
  reg signed [16:0] Radix22ButterflyG2_btf1_im_reg;  // sfix17
  reg signed [16:0] Radix22ButterflyG2_btf2_re_reg;  // sfix17
  reg signed [16:0] Radix22ButterflyG2_btf2_im_reg;  // sfix17
  reg signed [15:0] Radix22ButterflyG2_din_re_dly;  // sfix16
  reg signed [15:0] Radix22ButterflyG2_din_im_dly;  // sfix16
  reg  Radix22ButterflyG2_din_vld_dly;
  reg signed [15:0] Radix22ButterflyG2_x_re_dly;  // sfix16
  reg signed [15:0] Radix22ButterflyG2_x_im_dly;  // sfix16
  reg  Radix22ButterflyG2_x_vld_dly;
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_re_dly1;  // sfix16
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_im_dly1;  // sfix16
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_re_dly2;  // sfix16
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_im_dly2;  // sfix16
  reg  Radix22ButterflyG2_multiply_J_dly1;
  reg  Radix22ButterflyG2_procEnb_dly_next;
  reg  Radix22ButterflyG2_procEnb_dly1_next;
  reg  Radix22ButterflyG2_procEnb_dly2_next;
  reg signed [16:0] Radix22ButterflyG2_btf1_re_reg_next;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_btf1_im_reg_next;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_btf2_re_reg_next;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_btf2_im_reg_next;  // sfix17_En14
  reg signed [15:0] Radix22ButterflyG2_din_re_dly_next;  // sfix16_En14
  reg signed [15:0] Radix22ButterflyG2_din_im_dly_next;  // sfix16_En14
  reg  Radix22ButterflyG2_din_vld_dly_next;
  reg signed [15:0] Radix22ButterflyG2_x_re_dly_next;  // sfix16_En14
  reg signed [15:0] Radix22ButterflyG2_x_im_dly_next;  // sfix16_En14
  reg  Radix22ButterflyG2_x_vld_dly_next;
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_re_dly1_next;  // sfix16_En14
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_im_dly1_next;  // sfix16_En14
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_re_dly2_next;  // sfix16_En14
  reg signed [15:0] Radix22ButterflyG2_dinXTwdl_im_dly2_next;  // sfix16_En14
  reg  Radix22ButterflyG2_multiply_J_dly1_next;
  reg signed [15:0] xf_re;  // sfix16_En14
  reg signed [15:0] xf_im;  // sfix16_En14
  reg  xf_vld;
  reg signed [15:0] dinf_re;  // sfix16_En14
  reg signed [15:0] dinf_im;  // sfix16_En14
  reg  dinf_vld;
  reg signed [15:0] btf1_re;  // sfix16_En14
  reg signed [15:0] btf1_im;  // sfix16_En14
  reg signed [15:0] btf2_re;  // sfix16_En14
  reg signed [15:0] btf2_im;  // sfix16_En14
  reg  btfout_vld;
  reg signed [16:0] Radix22ButterflyG2_add_cast;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_add_cast_0;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_add_cast_1;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_add_cast_2;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_sub_cast;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_sub_cast_0;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_sub_cast_1;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_sub_cast_2;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_add_cast_3;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_add_cast_4;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_add_cast_5;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_add_cast_6;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_sub_cast_3;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_sub_cast_4;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_sub_cast_5;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_sub_cast_6;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_sra_temp;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_sra_temp_0;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_sra_temp_1;  // sfix17_En14
  reg signed [16:0] Radix22ButterflyG2_sra_temp_2;  // sfix17_En14


  assign btfin_vld = dout_1_1_vld & proc_2_enb;



  assign saveEnb =  ~ btfin_vld;



  assign dinVld = dout_1_1_vld & saveEnb;



  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          x_vld <= rd_2_Enb;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        x_vld_dly <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          x_vld_dly <= x_vld;
        end
      end
    end



  whdlOFDMTx_SimpleDualPortRAM_generic_block #(.AddrWidth(5),
                                               .DataWidth(16)
                                               )
                                             u_dataMEM_im_0_2 (.clk(clk),
                                                               .enb_1_32_0(enb_1_32_0),
                                                               .wr_din(wrData_im),
                                                               .wr_addr(wrAddr),
                                                               .wr_en(wrEnb),
                                                               .rd_addr(rd_2_Addr),
                                                               .rd_dout(x_im)
                                                               );

  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        x_im_dly <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          x_im_dly <= x_im;
        end
      end
    end



  whdlOFDMTx_SimpleDualPortRAM_generic_block #(.AddrWidth(5),
                                               .DataWidth(16)
                                               )
                                             u_dataMEM_re_0_2 (.clk(clk),
                                                               .enb_1_32_0(enb_1_32_0),
                                                               .wr_din(wrData_re),
                                                               .wr_addr(wrAddr),
                                                               .wr_en(wrEnb),
                                                               .rd_addr(rd_2_Addr),
                                                               .rd_dout(x_re)
                                                               );

  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        x_re_dly <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          x_re_dly <= x_re;
        end
      end
    end



  // Radix22ButterflyG2
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG2_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_procEnb_dly <= 1'b0;
        Radix22ButterflyG2_procEnb_dly1 <= 1'b0;
        Radix22ButterflyG2_procEnb_dly2 <= 1'b0;
        Radix22ButterflyG2_btf1_re_reg <= 17'sb00000000000000000;
        Radix22ButterflyG2_btf1_im_reg <= 17'sb00000000000000000;
        Radix22ButterflyG2_btf2_re_reg <= 17'sb00000000000000000;
        Radix22ButterflyG2_btf2_im_reg <= 17'sb00000000000000000;
        Radix22ButterflyG2_din_re_dly <= 16'sb0000000000000000;
        Radix22ButterflyG2_din_im_dly <= 16'sb0000000000000000;
        Radix22ButterflyG2_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_x_re_dly <= 16'sb0000000000000000;
        Radix22ButterflyG2_x_im_dly <= 16'sb0000000000000000;
        Radix22ButterflyG2_x_vld_dly <= 1'b0;
        Radix22ButterflyG2_dinXTwdl_re_dly1 <= 16'sb0000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly1 <= 16'sb0000000000000000;
        Radix22ButterflyG2_dinXTwdl_re_dly2 <= 16'sb0000000000000000;
        Radix22ButterflyG2_dinXTwdl_im_dly2 <= 16'sb0000000000000000;
        Radix22ButterflyG2_multiply_J_dly1 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          Radix22ButterflyG2_procEnb_dly <= Radix22ButterflyG2_procEnb_dly_next;
          Radix22ButterflyG2_procEnb_dly1 <= Radix22ButterflyG2_procEnb_dly1_next;
          Radix22ButterflyG2_procEnb_dly2 <= Radix22ButterflyG2_procEnb_dly2_next;
          Radix22ButterflyG2_btf1_re_reg <= Radix22ButterflyG2_btf1_re_reg_next;
          Radix22ButterflyG2_btf1_im_reg <= Radix22ButterflyG2_btf1_im_reg_next;
          Radix22ButterflyG2_btf2_re_reg <= Radix22ButterflyG2_btf2_re_reg_next;
          Radix22ButterflyG2_btf2_im_reg <= Radix22ButterflyG2_btf2_im_reg_next;
          Radix22ButterflyG2_din_re_dly <= Radix22ButterflyG2_din_re_dly_next;
          Radix22ButterflyG2_din_im_dly <= Radix22ButterflyG2_din_im_dly_next;
          Radix22ButterflyG2_din_vld_dly <= Radix22ButterflyG2_din_vld_dly_next;
          Radix22ButterflyG2_x_re_dly <= Radix22ButterflyG2_x_re_dly_next;
          Radix22ButterflyG2_x_im_dly <= Radix22ButterflyG2_x_im_dly_next;
          Radix22ButterflyG2_x_vld_dly <= Radix22ButterflyG2_x_vld_dly_next;
          Radix22ButterflyG2_dinXTwdl_re_dly1 <= Radix22ButterflyG2_dinXTwdl_re_dly1_next;
          Radix22ButterflyG2_dinXTwdl_im_dly1 <= Radix22ButterflyG2_dinXTwdl_im_dly1_next;
          Radix22ButterflyG2_dinXTwdl_re_dly2 <= Radix22ButterflyG2_dinXTwdl_re_dly2_next;
          Radix22ButterflyG2_dinXTwdl_im_dly2 <= Radix22ButterflyG2_dinXTwdl_im_dly2_next;
          Radix22ButterflyG2_multiply_J_dly1 <= Radix22ButterflyG2_multiply_J_dly1_next;
        end
      end
    end

  always @(Radix22ButterflyG2_btf1_im_reg, Radix22ButterflyG2_btf1_re_reg,
       Radix22ButterflyG2_btf2_im_reg, Radix22ButterflyG2_btf2_re_reg,
       Radix22ButterflyG2_dinXTwdl_im_dly1, Radix22ButterflyG2_dinXTwdl_im_dly2,
       Radix22ButterflyG2_dinXTwdl_re_dly1, Radix22ButterflyG2_dinXTwdl_re_dly2,
       Radix22ButterflyG2_din_im_dly, Radix22ButterflyG2_din_re_dly,
       Radix22ButterflyG2_din_vld_dly, Radix22ButterflyG2_multiply_J_dly1,
       Radix22ButterflyG2_procEnb_dly, Radix22ButterflyG2_procEnb_dly1,
       Radix22ButterflyG2_procEnb_dly2, Radix22ButterflyG2_x_im_dly,
       Radix22ButterflyG2_x_re_dly, Radix22ButterflyG2_x_vld_dly, btfin_vld,
       dinVld, dout_1_1_im, dout_1_1_re, multiply_2_J, x_im_dly, x_re_dly,
       x_vld_dly) begin
    Radix22ButterflyG2_add_cast = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast_0 = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast_1 = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast_2 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_0 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_1 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_2 = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast_3 = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast_4 = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast_5 = 17'sb00000000000000000;
    Radix22ButterflyG2_add_cast_6 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_3 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_4 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_5 = 17'sb00000000000000000;
    Radix22ButterflyG2_sub_cast_6 = 17'sb00000000000000000;
    Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_btf1_re_reg;
    Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_btf1_im_reg;
    Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_btf2_re_reg;
    Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_btf2_im_reg;
    Radix22ButterflyG2_x_re_dly_next = x_re_dly;
    Radix22ButterflyG2_x_im_dly_next = x_im_dly;
    Radix22ButterflyG2_x_vld_dly_next = x_vld_dly;
    Radix22ButterflyG2_din_re_dly_next = dout_1_1_re;
    Radix22ButterflyG2_din_im_dly_next = dout_1_1_im;
    Radix22ButterflyG2_din_vld_dly_next = dinVld;
    Radix22ButterflyG2_procEnb_dly2_next = Radix22ButterflyG2_procEnb_dly1;
    Radix22ButterflyG2_procEnb_dly1_next = Radix22ButterflyG2_procEnb_dly;
    Radix22ButterflyG2_procEnb_dly_next = btfin_vld;
    if (Radix22ButterflyG2_multiply_J_dly1) begin
      Radix22ButterflyG2_add_cast_1 = {x_re_dly[15], x_re_dly};
      Radix22ButterflyG2_add_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[15], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast_1 + Radix22ButterflyG2_add_cast_2;
      Radix22ButterflyG2_sub_cast_1 = {x_re_dly[15], x_re_dly};
      Radix22ButterflyG2_sub_cast_2 = {Radix22ButterflyG2_dinXTwdl_im_dly2[15], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast_1 - Radix22ButterflyG2_sub_cast_2;
      Radix22ButterflyG2_add_cast_5 = {x_im_dly[15], x_im_dly};
      Radix22ButterflyG2_add_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[15], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_add_cast_5 + Radix22ButterflyG2_add_cast_6;
      Radix22ButterflyG2_sub_cast_5 = {x_im_dly[15], x_im_dly};
      Radix22ButterflyG2_sub_cast_6 = {Radix22ButterflyG2_dinXTwdl_re_dly2[15], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_sub_cast_5 - Radix22ButterflyG2_sub_cast_6;
    end
    else begin
      Radix22ButterflyG2_add_cast = {x_re_dly[15], x_re_dly};
      Radix22ButterflyG2_add_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[15], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf1_re_reg_next = Radix22ButterflyG2_add_cast + Radix22ButterflyG2_add_cast_0;
      Radix22ButterflyG2_sub_cast = {x_re_dly[15], x_re_dly};
      Radix22ButterflyG2_sub_cast_0 = {Radix22ButterflyG2_dinXTwdl_re_dly2[15], Radix22ButterflyG2_dinXTwdl_re_dly2};
      Radix22ButterflyG2_btf2_re_reg_next = Radix22ButterflyG2_sub_cast - Radix22ButterflyG2_sub_cast_0;
      Radix22ButterflyG2_add_cast_3 = {x_im_dly[15], x_im_dly};
      Radix22ButterflyG2_add_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[15], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf1_im_reg_next = Radix22ButterflyG2_add_cast_3 + Radix22ButterflyG2_add_cast_4;
      Radix22ButterflyG2_sub_cast_3 = {x_im_dly[15], x_im_dly};
      Radix22ButterflyG2_sub_cast_4 = {Radix22ButterflyG2_dinXTwdl_im_dly2[15], Radix22ButterflyG2_dinXTwdl_im_dly2};
      Radix22ButterflyG2_btf2_im_reg_next = Radix22ButterflyG2_sub_cast_3 - Radix22ButterflyG2_sub_cast_4;
    end
    Radix22ButterflyG2_dinXTwdl_re_dly2_next = Radix22ButterflyG2_dinXTwdl_re_dly1;
    Radix22ButterflyG2_dinXTwdl_im_dly2_next = Radix22ButterflyG2_dinXTwdl_im_dly1;
    Radix22ButterflyG2_dinXTwdl_re_dly1_next = dout_1_1_re;
    Radix22ButterflyG2_dinXTwdl_im_dly1_next = dout_1_1_im;
    Radix22ButterflyG2_multiply_J_dly1_next = multiply_2_J;
    xf_re = Radix22ButterflyG2_x_re_dly;
    xf_im = Radix22ButterflyG2_x_im_dly;
    xf_vld = Radix22ButterflyG2_x_vld_dly;
    dinf_re = Radix22ButterflyG2_din_re_dly;
    dinf_im = Radix22ButterflyG2_din_im_dly;
    dinf_vld = Radix22ButterflyG2_din_vld_dly;
    Radix22ButterflyG2_sra_temp = Radix22ButterflyG2_btf1_re_reg >>> 8'd1;
    btf1_re = Radix22ButterflyG2_sra_temp[15:0];
    Radix22ButterflyG2_sra_temp_0 = Radix22ButterflyG2_btf1_im_reg >>> 8'd1;
    btf1_im = Radix22ButterflyG2_sra_temp_0[15:0];
    Radix22ButterflyG2_sra_temp_1 = Radix22ButterflyG2_btf2_re_reg >>> 8'd1;
    btf2_re = Radix22ButterflyG2_sra_temp_1[15:0];
    Radix22ButterflyG2_sra_temp_2 = Radix22ButterflyG2_btf2_im_reg >>> 8'd1;
    btf2_im = Radix22ButterflyG2_sra_temp_2[15:0];
    btfout_vld = Radix22ButterflyG2_procEnb_dly2;
  end



  whdlOFDMTx_SDFCommutator2 u_SDFCOMMUTATOR_2 (.clk(clk),
                                               .reset(reset),
                                               .enb_1_32_0(enb_1_32_0),
                                               .dout_1_1_vld(dout_1_1_vld),
                                               .xf_re(xf_re),  // sfix16_En14
                                               .xf_im(xf_im),  // sfix16_En14
                                               .xf_vld(xf_vld),
                                               .dinf_re(dinf_re),  // sfix16_En14
                                               .dinf_im(dinf_im),  // sfix16_En14
                                               .dinf_vld(dinf_vld),
                                               .btf1_re(btf1_re),  // sfix16_En14
                                               .btf1_im(btf1_im),  // sfix16_En14
                                               .btf2_re(btf2_re),  // sfix16_En14
                                               .btf2_im(btf2_im),  // sfix16_En14
                                               .btfout_vld(btfout_vld),
                                               .wrData_re(wrData_re),  // sfix16_En14
                                               .wrData_im(wrData_im),  // sfix16_En14
                                               .wrAddr(wrAddr),  // ufix5
                                               .wrEnb(wrEnb),
                                               .dout_2_1_re(dout_2_1_re),  // sfix16_En14
                                               .dout_2_1_im(dout_2_1_im),  // sfix16_En14
                                               .dout_2_1_vld(dout_2_1_vld)
                                               );

  assign dinXTwdl_2_1_vld = btfin_vld;

endmodule  // whdlOFDMTx_RADIX22FFT_SDF2_2

