// -------------------------------------------------------------
// 
// File Name: D:\OFDM\HDLImplementationOfDUCForLTEExample(Single Tone Output)\HDLImplementationOfDUCForLTEExample\hdlsrc\complex_upsampler\DUCforLTEHDL\castSection.v
// Created: 2023-05-25 17:45:33
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: castSection
// Source Path: DUCforLTEHDL/HDL_DUC/CICInterpolator/castSection
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module castSection
          (gcOut_re,
           gcOut_im,
           dataOut_re,
           dataOut_im);


  input   signed [19:0] gcOut_re;  // sfix20_En14
  input   signed [19:0] gcOut_im;  // sfix20_En14
  output  signed [17:0] dataOut_re;  // sfix18_En12
  output  signed [17:0] dataOut_im;  // sfix18_En12




  assign dataOut_re = gcOut_re[19:2];



  assign dataOut_im = gcOut_im[19:2];



endmodule  // castSection

