// -------------------------------------------------------------
// 
// File Name: D:\OFDM\HDLImplementationOfDUCForLTEExample(Single Tone Output)\HDLImplementationOfDUCForLTEExample\hdlsrc\complex_upsampler\DUCforLTEHDL\FIRFilter2_block1.v
// Created: 2023-05-25 17:45:34
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FIRFilter2_block1
// Source Path: DUCforLTEHDL/HDL_DUC/Lowpass Interpolator/DUCforLTEHDL/HDL_DUC/Lowpass Interpolator/FIRFilter2
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FIRFilter2_block1
          (clk,
           reset,
           enb,
           dataIn_re,
           dataIn_im,
           validIn,
           dataOut_re,
           dataOut_im,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn_re;  // sfix16_En15
  input   signed [15:0] dataIn_im;  // sfix16_En15
  input   validIn;
  output  signed [17:0] dataOut_re;  // sfix18_En14
  output  signed [17:0] dataOut_im;  // sfix18_En14
  output  validOut;


  wire signed [15:0] dinSM_re;  // sfix16_En15
  wire signed [15:0] dinSM_im;  // sfix16_En15
  wire dinVldSM;
  reg [3:0] nextDelayLineRdAddrReverse;  // ufix4
  reg [3:0] rdCountReverse_1;  // ufix4
  reg [3:0] nextDelayLineWrAddr;  // ufix4
  reg [3:0] wrCount_1;  // ufix4
  reg [3:0] nextDelayLineRdAddr;  // ufix4
  reg [3:0] rdCount_1;  // ufix4
  reg [3:0] nextSharingCount;  // ufix4
  reg [3:0] sharingCount_1;  // ufix4
  reg  delayLineValidInP;
  reg  lastPhaseStrobe;
  reg  delayLineShiftEnP;
  reg  delayLineShiftEn1_1;
  wire syncResetRst;
  reg  delayLineShiftEn2_1;
  reg  delayLineShiftEn3_1;
  reg  delayLineShiftEn4_1;
  reg  delayLineShiftEn5_1;
  reg  delayLineShiftEn6_1;
  reg  delayLineShiftEn7_1;
  reg  delayLineShiftEn8_1;
  reg  [0:6] validOutLookahead_reg;  // ufix1 [7]
  wire [0:6] validOutLookahead_reg_next;  // ufix1 [7]
  wire validOutLookahead_1;
  reg  vldOut_1;
  wire notValid;
  reg [3:0] rdAddr0_1;  // ufix4
  reg [3:0] rdAddr1;  // ufix4
  reg [3:0] rdAddr2;  // ufix4
  reg [3:0] rdAddr3;  // ufix4
  reg [3:0] rdAddr4;  // ufix4
  reg [3:0] rdAddr5;  // ufix4
  reg [3:0] rdAddr6;  // ufix4
  reg [3:0] rdAddr7;  // ufix4
  reg [3:0] rdAddr8;  // ufix4
  wire rdAddrEndNonZero;
  wire rdAddrEndZero;
  reg  [0:5] finalSumValidPipe_reg;  // ufix1 [6]
  wire [0:5] finalSumValidPipe_reg_next;  // ufix1 [6]
  wire accumulate;
  wire signed [32:0] accDataOut;  // sfix33_En30
  reg [3:0] wrAddrP;  // ufix4
  reg [3:0] rdAddrDelayLine0;  // ufix4
  wire signed [15:0] delayLineEnd0;  // sfix16_En15
  wire signed [15:0] delayLineDataOut0;  // sfix16_En15
  reg signed [15:0] delayLineDataIn1_1;  // sfix16_En15
  reg [3:0] wrAddr1;  // ufix4
  reg [3:0] rdAddrDelayLine1;  // ufix4
  wire signed [15:0] delayLineEnd1;  // sfix16_En15
  wire signed [15:0] delayLineDataOut1;  // sfix16_En15
  reg signed [15:0] delayLineDataIn2_1;  // sfix16_En15
  reg [3:0] wrAddr2;  // ufix4
  reg [3:0] rdAddrDelayLine2;  // ufix4
  wire signed [15:0] delayLineEnd2;  // sfix16_En15
  wire signed [15:0] delayLineDataOut2;  // sfix16_En15
  reg signed [15:0] delayLineDataIn3_1;  // sfix16_En15
  reg [3:0] wrAddr3;  // ufix4
  reg [3:0] rdAddrDelayLine3;  // ufix4
  wire signed [15:0] delayLineEnd3;  // sfix16_En15
  wire signed [15:0] delayLineDataOut3;  // sfix16_En15
  reg signed [15:0] delayLineDataIn4_1;  // sfix16_En15
  reg [3:0] wrAddr4;  // ufix4
  reg [3:0] rdAddrDelayLine4;  // ufix4
  wire signed [15:0] delayLineEnd4;  // sfix16_En15
  wire signed [15:0] delayLineDataOut4;  // sfix16_En15
  reg signed [15:0] delayLineDataIn5_1;  // sfix16_En15
  reg [3:0] wrAddr5;  // ufix4
  reg [3:0] rdAddrDelayLine5;  // ufix4
  wire signed [15:0] delayLineEnd5;  // sfix16_En15
  wire signed [15:0] delayLineDataOut5;  // sfix16_En15
  reg signed [15:0] delayLineDataIn6_1;  // sfix16_En15
  reg [3:0] wrAddr6;  // ufix4
  reg [3:0] rdAddrDelayLine6;  // ufix4
  wire signed [15:0] delayLineEnd6;  // sfix16_En15
  wire signed [15:0] delayLineDataOut6;  // sfix16_En15
  reg signed [15:0] delayLineDataIn7_1;  // sfix16_En15
  reg [3:0] wrAddr7;  // ufix4
  reg [3:0] rdAddrDelayLine7;  // ufix4
  wire signed [15:0] delayLineEnd7;  // sfix16_En15
  wire signed [15:0] delayLineDataOut7;  // sfix16_En15
  reg signed [15:0] delayLineDataIn8_1;  // sfix16_En15
  reg [3:0] wrAddr8;  // ufix4
  reg [3:0] rdAddrDelayLine8;  // ufix4
  wire signed [15:0] delayLineEnd8deadOut;  // sfix16_En15
  wire signed [15:0] delayLineDataOut8;  // sfix16_En15
  reg signed [15:0] coeffTableOut8;  // sfix16_En15
  reg signed [15:0] coeffTableRegP8_1;  // sfix16_En15
  reg signed [15:0] coeffTableOut7;  // sfix16_En15
  reg signed [15:0] coeffTableRegP7_1;  // sfix16_En15
  reg signed [15:0] coeffTableOut6;  // sfix16_En15
  reg signed [15:0] coeffTableRegP6_1;  // sfix16_En15
  reg signed [15:0] coeffTableOut5;  // sfix16_En15
  reg signed [15:0] coeffTableRegP5_1;  // sfix16_En15
  reg signed [15:0] coeffTableOut4;  // sfix16_En15
  reg signed [15:0] coeffTableRegP4_1;  // sfix16_En15
  reg signed [15:0] coeffTableOut3;  // sfix16_En15
  reg signed [15:0] coeffTableRegP3_1;  // sfix16_En15
  reg signed [15:0] coeffTableOut2;  // sfix16_En15
  reg signed [15:0] coeffTableRegP2_1;  // sfix16_En15
  reg signed [15:0] coeffTableOut1;  // sfix16_En15
  reg signed [15:0] coeffTableRegP1_1;  // sfix16_En15
  reg signed [15:0] coeffTableOut0;  // sfix16_En15
  reg signed [15:0] coeffTableRegP0_1;  // sfix16_En15
  wire signed [32:0] sumIn;  // sfix33_En30
  wire signed [32:0] sumOut;  // sfix33_En30
  wire signed [32:0] sumOut_0;  // sfix33_En30
  wire signed [32:0] sumOut_1;  // sfix33_En30
  wire signed [32:0] sumOut_2;  // sfix33_En30
  wire signed [32:0] sumOut_3;  // sfix33_En30
  wire signed [32:0] sumOut_4;  // sfix33_En30
  wire signed [32:0] sumOut_5;  // sfix33_En30
  wire signed [32:0] sumOut_6;  // sfix33_En30
  wire signed [32:0] sumOut_7;  // sfix33_En30
  reg signed [32:0] sumOutReg_1;  // sfix33_En30
  reg signed [32:0] accDataOut_1;  // sfix33_En30
  wire signed [32:0] accSwitchOut;  // sfix33_En30
  wire signed [32:0] accAdderOut;  // sfix33_En30
  wire signed [17:0] converterOut;  // sfix18_En14
  reg signed [17:0] dout_re_1;  // sfix18_En14
  reg  [0:6] validOutLookahead_reg_1;  // ufix1 [7]
  wire [0:6] validOutLookahead_reg_next_1;  // ufix1 [7]
  wire validOutLookahead_3;
  wire rdAddrEndNonZero_1;
  wire rdAddrEndZero_1;
  reg  [0:5] finalSumValidPipe_reg_1;  // ufix1 [6]
  wire [0:5] finalSumValidPipe_reg_next_1;  // ufix1 [6]
  wire accumulate_1;
  wire signed [32:0] accDataOut_3;  // sfix33_En30
  wire signed [15:0] delayLineEnd0_1;  // sfix16_En15
  wire signed [15:0] delayLineDataOut0_1;  // sfix16_En15
  reg signed [15:0] delayLineDataIn1_3;  // sfix16_En15
  wire signed [15:0] delayLineEnd1_1;  // sfix16_En15
  wire signed [15:0] delayLineDataOut1_1;  // sfix16_En15
  reg signed [15:0] delayLineDataIn2_3;  // sfix16_En15
  wire signed [15:0] delayLineEnd2_1;  // sfix16_En15
  wire signed [15:0] delayLineDataOut2_1;  // sfix16_En15
  reg signed [15:0] delayLineDataIn3_3;  // sfix16_En15
  wire signed [15:0] delayLineEnd3_1;  // sfix16_En15
  wire signed [15:0] delayLineDataOut3_1;  // sfix16_En15
  reg signed [15:0] delayLineDataIn4_3;  // sfix16_En15
  wire signed [15:0] delayLineEnd4_1;  // sfix16_En15
  wire signed [15:0] delayLineDataOut4_1;  // sfix16_En15
  reg signed [15:0] delayLineDataIn5_3;  // sfix16_En15
  wire signed [15:0] delayLineEnd5_1;  // sfix16_En15
  wire signed [15:0] delayLineDataOut5_1;  // sfix16_En15
  reg signed [15:0] delayLineDataIn6_3;  // sfix16_En15
  wire signed [15:0] delayLineEnd6_1;  // sfix16_En15
  wire signed [15:0] delayLineDataOut6_1;  // sfix16_En15
  reg signed [15:0] delayLineDataIn7_3;  // sfix16_En15
  wire signed [15:0] delayLineEnd7_1;  // sfix16_En15
  wire signed [15:0] delayLineDataOut7_1;  // sfix16_En15
  reg signed [15:0] delayLineDataIn8_3;  // sfix16_En15
  wire signed [15:0] delayLineEnd8deadOut_1;  // sfix16_En15
  wire signed [15:0] delayLineDataOut8_1;  // sfix16_En15
  reg signed [15:0] coeffTableOut8_1;  // sfix16_En15
  reg signed [15:0] coeffTableRegP8_3;  // sfix16_En15
  reg signed [15:0] coeffTableOut7_1;  // sfix16_En15
  reg signed [15:0] coeffTableRegP7_3;  // sfix16_En15
  reg signed [15:0] coeffTableOut6_1;  // sfix16_En15
  reg signed [15:0] coeffTableRegP6_3;  // sfix16_En15
  reg signed [15:0] coeffTableOut5_1;  // sfix16_En15
  reg signed [15:0] coeffTableRegP5_3;  // sfix16_En15
  reg signed [15:0] coeffTableOut4_1;  // sfix16_En15
  reg signed [15:0] coeffTableRegP4_3;  // sfix16_En15
  reg signed [15:0] coeffTableOut3_1;  // sfix16_En15
  reg signed [15:0] coeffTableRegP3_3;  // sfix16_En15
  reg signed [15:0] coeffTableOut2_1;  // sfix16_En15
  reg signed [15:0] coeffTableRegP2_3;  // sfix16_En15
  reg signed [15:0] coeffTableOut1_1;  // sfix16_En15
  reg signed [15:0] coeffTableRegP1_3;  // sfix16_En15
  reg signed [15:0] coeffTableOut0_1;  // sfix16_En15
  reg signed [15:0] coeffTableRegP0_3;  // sfix16_En15
  wire signed [32:0] sumIn_1;  // sfix33_En30
  wire signed [32:0] sumOut_8;  // sfix33_En30
  wire signed [32:0] sumOut_0_1;  // sfix33_En30
  wire signed [32:0] sumOut_1_1;  // sfix33_En30
  wire signed [32:0] sumOut_2_1;  // sfix33_En30
  wire signed [32:0] sumOut_3_1;  // sfix33_En30
  wire signed [32:0] sumOut_4_1;  // sfix33_En30
  wire signed [32:0] sumOut_5_1;  // sfix33_En30
  wire signed [32:0] sumOut_6_1;  // sfix33_En30
  wire signed [32:0] sumOut_7_1;  // sfix33_En30
  reg signed [32:0] sumOutReg_3;  // sfix33_En30
  reg signed [32:0] accDataOut_4;  // sfix33_En30
  wire signed [32:0] accSwitchOut_1;  // sfix33_En30
  wire signed [32:0] accAdderOut_1;  // sfix33_En30
  wire signed [17:0] converterOut_1;  // sfix18_En14
  reg signed [17:0] dout_im_1;  // sfix18_En14
  wire signed [17:0] dataZero;  // sfix18_En14
  wire signed [17:0] dataZero_dtc_re;  // sfix18_En14
  wire signed [17:0] dataZero_dtc_im;  // sfix18_En14
  wire signed [17:0] dout_cmplxSW_re;  // sfix18_En14
  wire signed [17:0] dout_cmplxSW_im;  // sfix18_En14
  reg [3:0] InputControl_out4_0;  // ufix4

  initial begin
    coeffTableRegP8_1 = 16'sb0000000000000000;
    coeffTableRegP7_1 = 16'sb0000000000000000;
    coeffTableRegP6_1 = 16'sb0000000000000000;
    coeffTableRegP5_1 = 16'sb0000000000000000;
    coeffTableRegP4_1 = 16'sb0000000000000000;
    coeffTableRegP3_1 = 16'sb0000000000000000;
    coeffTableRegP2_1 = 16'sb0000000000000000;
    coeffTableRegP1_1 = 16'sb0000000000000000;
    coeffTableRegP0_1 = 16'sb0000000000000000;
    coeffTableRegP8_3 = 16'sb0000000000000000;
    coeffTableRegP7_3 = 16'sb0000000000000000;
    coeffTableRegP6_3 = 16'sb0000000000000000;
    coeffTableRegP5_3 = 16'sb0000000000000000;
    coeffTableRegP4_3 = 16'sb0000000000000000;
    coeffTableRegP3_3 = 16'sb0000000000000000;
    coeffTableRegP2_3 = 16'sb0000000000000000;
    coeffTableRegP1_3 = 16'sb0000000000000000;
    coeffTableRegP0_3 = 16'sb0000000000000000;
  end

  FirRdyLogic_block4 u_firRdyLogic (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .dataIn_re(dataIn_re),  // sfix16_En15
                                    .dataIn_im(dataIn_im),  // sfix16_En15
                                    .validIn(validIn),
                                    .dinSM_re(dinSM_re),  // sfix16_En15
                                    .dinSM_im(dinSM_im),  // sfix16_En15
                                    .dinVldSM(dinVldSM)
                                    );

  always @(posedge clk or posedge reset)
    begin : rdCountReverse_process
      if (reset == 1'b1) begin
        rdCountReverse_1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdCountReverse_1 <= nextDelayLineRdAddrReverse;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrCount_process
      if (reset == 1'b1) begin
        wrCount_1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrCount_1 <= nextDelayLineWrAddr;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdCount_process
      if (reset == 1'b1) begin
        rdCount_1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdCount_1 <= nextDelayLineRdAddr;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : sharingCount_process
      if (reset == 1'b1) begin
        sharingCount_1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          sharingCount_1 <= nextSharingCount;
        end
      end
    end



  // Input control counter combinatorial logic
  always @(dinVldSM, rdCountReverse_1, rdCount_1, sharingCount_1, wrCount_1) begin
    delayLineValidInP = (sharingCount_1 == 4'b0000) && (dinVldSM == 1'b1);
    lastPhaseStrobe = sharingCount_1 == 4'b1111;
    if ((dinVldSM == 1'b1) || (sharingCount_1 > 4'b0000)) begin
      if (sharingCount_1 == 4'b1111) begin
        nextSharingCount = 4'b0000;
      end
      else begin
        nextSharingCount = sharingCount_1 + 4'b0001;
      end
    end
    else begin
      nextSharingCount = sharingCount_1;
    end
    if (dinVldSM == 1'b1) begin
      if (wrCount_1 == 4'b1111) begin
        InputControl_out4_0 = 4'b0000;
      end
      else begin
        InputControl_out4_0 = wrCount_1 + 4'b0001;
      end
    end
    else begin
      InputControl_out4_0 = wrCount_1;
    end
    if ((rdCount_1 != InputControl_out4_0) || (dinVldSM == 1'b1)) begin
      if (rdCount_1 == 4'b0000) begin
        nextDelayLineRdAddr = 4'b1111;
      end
      else begin
        nextDelayLineRdAddr = rdCount_1 - 4'b0001;
      end
    end
    else begin
      nextDelayLineRdAddr = rdCount_1;
    end
    if ((sharingCount_1 > 4'b0000) || (dinVldSM == 1'b1)) begin
      if (sharingCount_1 == 4'b1111) begin
        if (wrCount_1 == 4'b1111) begin
          nextDelayLineRdAddrReverse = 4'b0000;
        end
        else begin
          nextDelayLineRdAddrReverse = wrCount_1 + 4'b0001;
        end
      end
      else if (rdCountReverse_1 == 4'b1111) begin
        nextDelayLineRdAddrReverse = 4'b0000;
      end
      else begin
        nextDelayLineRdAddrReverse = rdCountReverse_1 + 4'b0001;
      end
    end
    else begin
      nextDelayLineRdAddrReverse = rdCountReverse_1;
    end
    nextDelayLineWrAddr = InputControl_out4_0;
  end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn0_process
      if (reset == 1'b1) begin
        delayLineShiftEnP <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEnP <= lastPhaseStrobe;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn1_process
      if (reset == 1'b1) begin
        delayLineShiftEn1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          delayLineShiftEn1_1 <= delayLineShiftEnP;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn2_process
      if (reset == 1'b1) begin
        delayLineShiftEn2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn2_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn2_1 <= delayLineShiftEn1_1;
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn3_process
      if (reset == 1'b1) begin
        delayLineShiftEn3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn3_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn3_1 <= delayLineShiftEn2_1;
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn4_process
      if (reset == 1'b1) begin
        delayLineShiftEn4_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn4_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn4_1 <= delayLineShiftEn3_1;
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn5_process
      if (reset == 1'b1) begin
        delayLineShiftEn5_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn5_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn5_1 <= delayLineShiftEn4_1;
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn6_process
      if (reset == 1'b1) begin
        delayLineShiftEn6_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn6_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn6_1 <= delayLineShiftEn5_1;
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn7_process
      if (reset == 1'b1) begin
        delayLineShiftEn7_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn7_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn7_1 <= delayLineShiftEn6_1;
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : delayLineShiftEn8_process
      if (reset == 1'b1) begin
        delayLineShiftEn8_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncResetRst == 1'b1) begin
            delayLineShiftEn8_1 <= 1'b0;
          end
          else begin
            delayLineShiftEn8_1 <= delayLineShiftEn7_1;
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : validOutLookahead_process
      if (reset == 1'b1) begin
        validOutLookahead_reg[0] <= 1'b0;
        validOutLookahead_reg[1] <= 1'b0;
        validOutLookahead_reg[2] <= 1'b0;
        validOutLookahead_reg[3] <= 1'b0;
        validOutLookahead_reg[4] <= 1'b0;
        validOutLookahead_reg[5] <= 1'b0;
        validOutLookahead_reg[6] <= 1'b0;
      end
      else begin
        if (enb) begin
          validOutLookahead_reg[0] <= validOutLookahead_reg_next[0];
          validOutLookahead_reg[1] <= validOutLookahead_reg_next[1];
          validOutLookahead_reg[2] <= validOutLookahead_reg_next[2];
          validOutLookahead_reg[3] <= validOutLookahead_reg_next[3];
          validOutLookahead_reg[4] <= validOutLookahead_reg_next[4];
          validOutLookahead_reg[5] <= validOutLookahead_reg_next[5];
          validOutLookahead_reg[6] <= validOutLookahead_reg_next[6];
        end
      end
    end

  assign validOutLookahead_1 = validOutLookahead_reg[6];
  assign validOutLookahead_reg_next[0] = delayLineShiftEn8_1;
  assign validOutLookahead_reg_next[1] = validOutLookahead_reg[0];
  assign validOutLookahead_reg_next[2] = validOutLookahead_reg[1];
  assign validOutLookahead_reg_next[3] = validOutLookahead_reg[2];
  assign validOutLookahead_reg_next[4] = validOutLookahead_reg[3];
  assign validOutLookahead_reg_next[5] = validOutLookahead_reg[4];
  assign validOutLookahead_reg_next[6] = validOutLookahead_reg[5];



  always @(posedge clk or posedge reset)
    begin : vldOut_process
      if (reset == 1'b1) begin
        vldOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          vldOut_1 <= validOutLookahead_1;
        end
      end
    end



  assign notValid =  ~ vldOut_1;



  always @(posedge clk or posedge reset)
    begin : rdAddr0_process
      if (reset == 1'b1) begin
        rdAddr0_1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr0_1 <= sharingCount_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr0_2_process
      if (reset == 1'b1) begin
        rdAddr1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr1 <= rdAddr0_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr1_1_process
      if (reset == 1'b1) begin
        rdAddr2 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr2 <= rdAddr1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr2_1_process
      if (reset == 1'b1) begin
        rdAddr3 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr3 <= rdAddr2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr3_1_process
      if (reset == 1'b1) begin
        rdAddr4 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr4 <= rdAddr3;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr4_1_process
      if (reset == 1'b1) begin
        rdAddr5 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr5 <= rdAddr4;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr5_1_process
      if (reset == 1'b1) begin
        rdAddr6 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr6 <= rdAddr5;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr6_1_process
      if (reset == 1'b1) begin
        rdAddr7 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr7 <= rdAddr6;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddr7_1_process
      if (reset == 1'b1) begin
        rdAddr8 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddr8 <= rdAddr7;
        end
      end
    end



  assign rdAddrEndNonZero = rdAddr8 != 4'b0000;



  assign rdAddrEndZero =  ~ rdAddrEndNonZero;



  always @(posedge clk or posedge reset)
    begin : finalSumValidPipe_process
      if (reset == 1'b1) begin
        finalSumValidPipe_reg[0] <= 1'b0;
        finalSumValidPipe_reg[1] <= 1'b0;
        finalSumValidPipe_reg[2] <= 1'b0;
        finalSumValidPipe_reg[3] <= 1'b0;
        finalSumValidPipe_reg[4] <= 1'b0;
        finalSumValidPipe_reg[5] <= 1'b0;
      end
      else begin
        if (enb) begin
          finalSumValidPipe_reg[0] <= finalSumValidPipe_reg_next[0];
          finalSumValidPipe_reg[1] <= finalSumValidPipe_reg_next[1];
          finalSumValidPipe_reg[2] <= finalSumValidPipe_reg_next[2];
          finalSumValidPipe_reg[3] <= finalSumValidPipe_reg_next[3];
          finalSumValidPipe_reg[4] <= finalSumValidPipe_reg_next[4];
          finalSumValidPipe_reg[5] <= finalSumValidPipe_reg_next[5];
        end
      end
    end

  assign accumulate = finalSumValidPipe_reg[5];
  assign finalSumValidPipe_reg_next[0] = rdAddrEndZero;
  assign finalSumValidPipe_reg_next[1] = finalSumValidPipe_reg[0];
  assign finalSumValidPipe_reg_next[2] = finalSumValidPipe_reg[1];
  assign finalSumValidPipe_reg_next[3] = finalSumValidPipe_reg[2];
  assign finalSumValidPipe_reg_next[4] = finalSumValidPipe_reg[3];
  assign finalSumValidPipe_reg_next[5] = finalSumValidPipe_reg[4];



  assign accDataOut = 33'sh000000000;



  always @(posedge clk or posedge reset)
    begin : wrAddr_process
      if (reset == 1'b1) begin
        wrAddrP <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddrP <= wrCount_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine_process
      if (reset == 1'b1) begin
        rdAddrDelayLine0 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine0 <= rdCount_1;
        end
      end
    end



  Addressable_Delay_Line_block17 u_delayLine0 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .dataIn(dinSM_re),  // sfix16_En15
                                               .wrEn(delayLineValidInP),
                                               .wrAddr(wrAddrP),  // ufix4
                                               .rdAddr(rdAddrDelayLine0),  // ufix4
                                               .delayLineEnd(delayLineEnd0),  // sfix16_En15
                                               .dataOut(delayLineDataOut0)  // sfix16_En15
                                               );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn1_process
      if (reset == 1'b1) begin
        delayLineDataIn1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn1_1 <= delayLineEnd0;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrAddr0_process
      if (reset == 1'b1) begin
        wrAddr1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddr1 <= wrAddrP;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine0_1_process
      if (reset == 1'b1) begin
        rdAddrDelayLine1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine1 <= rdAddrDelayLine0;
        end
      end
    end



  Addressable_Delay_Line_block17 u_delayLine1 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .dataIn(delayLineDataIn1_1),  // sfix16_En15
                                               .wrEn(delayLineShiftEn1_1),
                                               .wrAddr(wrAddr1),  // ufix4
                                               .rdAddr(rdAddrDelayLine1),  // ufix4
                                               .delayLineEnd(delayLineEnd1),  // sfix16_En15
                                               .dataOut(delayLineDataOut1)  // sfix16_En15
                                               );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn2_process
      if (reset == 1'b1) begin
        delayLineDataIn2_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn2_1 <= delayLineEnd1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrAddr1_1_process
      if (reset == 1'b1) begin
        wrAddr2 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddr2 <= wrAddr1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine1_1_process
      if (reset == 1'b1) begin
        rdAddrDelayLine2 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine2 <= rdAddrDelayLine1;
        end
      end
    end



  Addressable_Delay_Line_block17 u_delayLine2 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .dataIn(delayLineDataIn2_1),  // sfix16_En15
                                               .wrEn(delayLineShiftEn2_1),
                                               .wrAddr(wrAddr2),  // ufix4
                                               .rdAddr(rdAddrDelayLine2),  // ufix4
                                               .delayLineEnd(delayLineEnd2),  // sfix16_En15
                                               .dataOut(delayLineDataOut2)  // sfix16_En15
                                               );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn3_process
      if (reset == 1'b1) begin
        delayLineDataIn3_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn3_1 <= delayLineEnd2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrAddr2_1_process
      if (reset == 1'b1) begin
        wrAddr3 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddr3 <= wrAddr2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine2_1_process
      if (reset == 1'b1) begin
        rdAddrDelayLine3 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine3 <= rdAddrDelayLine2;
        end
      end
    end



  Addressable_Delay_Line_block17 u_delayLine3 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .dataIn(delayLineDataIn3_1),  // sfix16_En15
                                               .wrEn(delayLineShiftEn3_1),
                                               .wrAddr(wrAddr3),  // ufix4
                                               .rdAddr(rdAddrDelayLine3),  // ufix4
                                               .delayLineEnd(delayLineEnd3),  // sfix16_En15
                                               .dataOut(delayLineDataOut3)  // sfix16_En15
                                               );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn4_process
      if (reset == 1'b1) begin
        delayLineDataIn4_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn4_1 <= delayLineEnd3;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrAddr3_1_process
      if (reset == 1'b1) begin
        wrAddr4 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddr4 <= wrAddr3;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine3_1_process
      if (reset == 1'b1) begin
        rdAddrDelayLine4 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine4 <= rdAddrDelayLine3;
        end
      end
    end



  Addressable_Delay_Line_block17 u_delayLine4 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .dataIn(delayLineDataIn4_1),  // sfix16_En15
                                               .wrEn(delayLineShiftEn4_1),
                                               .wrAddr(wrAddr4),  // ufix4
                                               .rdAddr(rdAddrDelayLine4),  // ufix4
                                               .delayLineEnd(delayLineEnd4),  // sfix16_En15
                                               .dataOut(delayLineDataOut4)  // sfix16_En15
                                               );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn5_process
      if (reset == 1'b1) begin
        delayLineDataIn5_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn5_1 <= delayLineEnd4;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrAddr4_1_process
      if (reset == 1'b1) begin
        wrAddr5 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddr5 <= wrAddr4;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine4_1_process
      if (reset == 1'b1) begin
        rdAddrDelayLine5 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine5 <= rdAddrDelayLine4;
        end
      end
    end



  Addressable_Delay_Line_block17 u_delayLine5 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .dataIn(delayLineDataIn5_1),  // sfix16_En15
                                               .wrEn(delayLineShiftEn5_1),
                                               .wrAddr(wrAddr5),  // ufix4
                                               .rdAddr(rdAddrDelayLine5),  // ufix4
                                               .delayLineEnd(delayLineEnd5),  // sfix16_En15
                                               .dataOut(delayLineDataOut5)  // sfix16_En15
                                               );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn6_process
      if (reset == 1'b1) begin
        delayLineDataIn6_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn6_1 <= delayLineEnd5;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrAddr5_1_process
      if (reset == 1'b1) begin
        wrAddr6 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddr6 <= wrAddr5;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine5_1_process
      if (reset == 1'b1) begin
        rdAddrDelayLine6 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine6 <= rdAddrDelayLine5;
        end
      end
    end



  Addressable_Delay_Line_block17 u_delayLine6 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .dataIn(delayLineDataIn6_1),  // sfix16_En15
                                               .wrEn(delayLineShiftEn6_1),
                                               .wrAddr(wrAddr6),  // ufix4
                                               .rdAddr(rdAddrDelayLine6),  // ufix4
                                               .delayLineEnd(delayLineEnd6),  // sfix16_En15
                                               .dataOut(delayLineDataOut6)  // sfix16_En15
                                               );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn7_process
      if (reset == 1'b1) begin
        delayLineDataIn7_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn7_1 <= delayLineEnd6;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrAddr6_1_process
      if (reset == 1'b1) begin
        wrAddr7 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddr7 <= wrAddr6;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine6_1_process
      if (reset == 1'b1) begin
        rdAddrDelayLine7 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine7 <= rdAddrDelayLine6;
        end
      end
    end



  Addressable_Delay_Line_block17 u_delayLine7 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .dataIn(delayLineDataIn7_1),  // sfix16_En15
                                               .wrEn(delayLineShiftEn7_1),
                                               .wrAddr(wrAddr7),  // ufix4
                                               .rdAddr(rdAddrDelayLine7),  // ufix4
                                               .delayLineEnd(delayLineEnd7),  // sfix16_En15
                                               .dataOut(delayLineDataOut7)  // sfix16_En15
                                               );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn8_process
      if (reset == 1'b1) begin
        delayLineDataIn8_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn8_1 <= delayLineEnd7;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : wrAddr7_1_process
      if (reset == 1'b1) begin
        wrAddr8 <= 4'b0000;
      end
      else begin
        if (enb) begin
          wrAddr8 <= wrAddr7;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : rdAddrDelayLine7_1_process
      if (reset == 1'b1) begin
        rdAddrDelayLine8 <= 4'b0000;
      end
      else begin
        if (enb) begin
          rdAddrDelayLine8 <= rdAddrDelayLine7;
        end
      end
    end



  Addressable_Delay_Line_block17 u_delayLine8 (.clk(clk),
                                               .reset(reset),
                                               .enb(enb),
                                               .dataIn(delayLineDataIn8_1),  // sfix16_En15
                                               .wrEn(delayLineShiftEn8_1),
                                               .wrAddr(wrAddr8),  // ufix4
                                               .rdAddr(rdAddrDelayLine8),  // ufix4
                                               .delayLineEnd(delayLineEnd8deadOut),  // sfix16_En15
                                               .dataOut(delayLineDataOut8)  // sfix16_En15
                                               );

  // Coefficient table for multiplier8
  always @(rdAddr8) begin
    case ( rdAddr8)
      4'b0000 :
        begin
          coeffTableOut8 = 16'sb0000000000100101;
        end
      4'b0001 :
        begin
          coeffTableOut8 = 16'sb1111111111011100;
        end
      4'b0010 :
        begin
          coeffTableOut8 = 16'sb0000000000100011;
        end
      4'b0011 :
        begin
          coeffTableOut8 = 16'sb1111111111011110;
        end
      4'b0100 :
        begin
          coeffTableOut8 = 16'sb0000000000100001;
        end
      4'b0101 :
        begin
          coeffTableOut8 = 16'sb1111111111100000;
        end
      4'b0110 :
        begin
          coeffTableOut8 = 16'sb0000000000011110;
        end
      4'b0111 :
        begin
          coeffTableOut8 = 16'sb1111111111100011;
        end
      4'b1000 :
        begin
          coeffTableOut8 = 16'sb0000000000011011;
        end
      4'b1001 :
        begin
          coeffTableOut8 = 16'sb1111111111100001;
        end
      4'b1010 :
        begin
          coeffTableOut8 = 16'sb0000000000010011;
        end
      4'b1011 :
        begin
          coeffTableOut8 = 16'sb1111111110100010;
        end
      4'b1100 :
        begin
          coeffTableOut8 = 16'sb1111111111110010;
        end
      4'b1101 :
        begin
          coeffTableOut8 = 16'sb0000000000000000;
        end
      4'b1110 :
        begin
          coeffTableOut8 = 16'sb0000000000000000;
        end
      4'b1111 :
        begin
          coeffTableOut8 = 16'sb0000000000000000;
        end
      default :
        begin
          coeffTableOut8 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP8_process
      if (enb) begin
        coeffTableRegP8_1 <= coeffTableOut8;
      end
    end



  // Coefficient table for multiplier7
  always @(rdAddr7) begin
    case ( rdAddr7)
      4'b0000 :
        begin
          coeffTableOut7 = 16'sb1111111111011110;
        end
      4'b0001 :
        begin
          coeffTableOut7 = 16'sb0000000000011000;
        end
      4'b0010 :
        begin
          coeffTableOut7 = 16'sb1111111111110010;
        end
      4'b0011 :
        begin
          coeffTableOut7 = 16'sb0000000000000110;
        end
      4'b0100 :
        begin
          coeffTableOut7 = 16'sb0000000000000010;
        end
      4'b0101 :
        begin
          coeffTableOut7 = 16'sb1111111111111000;
        end
      4'b0110 :
        begin
          coeffTableOut7 = 16'sb0000000000001110;
        end
      4'b0111 :
        begin
          coeffTableOut7 = 16'sb1111111111101100;
        end
      4'b1000 :
        begin
          coeffTableOut7 = 16'sb0000000000011000;
        end
      4'b1001 :
        begin
          coeffTableOut7 = 16'sb1111111111100100;
        end
      4'b1010 :
        begin
          coeffTableOut7 = 16'sb0000000000011111;
        end
      4'b1011 :
        begin
          coeffTableOut7 = 16'sb1111111111011111;
        end
      4'b1100 :
        begin
          coeffTableOut7 = 16'sb0000000000100011;
        end
      4'b1101 :
        begin
          coeffTableOut7 = 16'sb1111111111011100;
        end
      4'b1110 :
        begin
          coeffTableOut7 = 16'sb0000000000100101;
        end
      4'b1111 :
        begin
          coeffTableOut7 = 16'sb1111111111011011;
        end
      default :
        begin
          coeffTableOut7 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP7_process
      if (enb) begin
        coeffTableRegP7_1 <= coeffTableOut7;
      end
    end



  // Coefficient table for multiplier6
  always @(rdAddr6) begin
    case ( rdAddr6)
      4'b0000 :
        begin
          coeffTableOut6 = 16'sb1111111011001010;
        end
      4'b0001 :
        begin
          coeffTableOut6 = 16'sb0000000100100001;
        end
      4'b0010 :
        begin
          coeffTableOut6 = 16'sb1111111011110101;
        end
      4'b0011 :
        begin
          coeffTableOut6 = 16'sb0000000011110110;
        end
      4'b0100 :
        begin
          coeffTableOut6 = 16'sb1111111100011111;
        end
      4'b0101 :
        begin
          coeffTableOut6 = 16'sb0000000011001101;
        end
      4'b0110 :
        begin
          coeffTableOut6 = 16'sb1111111101000110;
        end
      4'b0111 :
        begin
          coeffTableOut6 = 16'sb0000000010100111;
        end
      4'b1000 :
        begin
          coeffTableOut6 = 16'sb1111111101101011;
        end
      4'b1001 :
        begin
          coeffTableOut6 = 16'sb0000000010000100;
        end
      4'b1010 :
        begin
          coeffTableOut6 = 16'sb1111111110001101;
        end
      4'b1011 :
        begin
          coeffTableOut6 = 16'sb0000000001100011;
        end
      4'b1100 :
        begin
          coeffTableOut6 = 16'sb1111111110101011;
        end
      4'b1101 :
        begin
          coeffTableOut6 = 16'sb0000000001000111;
        end
      4'b1110 :
        begin
          coeffTableOut6 = 16'sb1111111111000110;
        end
      4'b1111 :
        begin
          coeffTableOut6 = 16'sb0000000000101101;
        end
      default :
        begin
          coeffTableOut6 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP6_process
      if (enb) begin
        coeffTableRegP6_1 <= coeffTableOut6;
      end
    end



  // Coefficient table for multiplier5
  always @(rdAddr5) begin
    case ( rdAddr5)
      4'b0000 :
        begin
          coeffTableOut5 = 16'sb1111110110001000;
        end
      4'b0001 :
        begin
          coeffTableOut5 = 16'sb0000001001101001;
        end
      4'b0010 :
        begin
          coeffTableOut5 = 16'sb1111110110100111;
        end
      4'b0011 :
        begin
          coeffTableOut5 = 16'sb0000001001001000;
        end
      4'b0100 :
        begin
          coeffTableOut5 = 16'sb1111110111001010;
        end
      4'b0101 :
        begin
          coeffTableOut5 = 16'sb0000001000100011;
        end
      4'b0110 :
        begin
          coeffTableOut5 = 16'sb1111110111110000;
        end
      4'b0111 :
        begin
          coeffTableOut5 = 16'sb0000000111111011;
        end
      4'b1000 :
        begin
          coeffTableOut5 = 16'sb1111111000011001;
        end
      4'b1001 :
        begin
          coeffTableOut5 = 16'sb0000000111010001;
        end
      4'b1010 :
        begin
          coeffTableOut5 = 16'sb1111111001000100;
        end
      4'b1011 :
        begin
          coeffTableOut5 = 16'sb0000000110100110;
        end
      4'b1100 :
        begin
          coeffTableOut5 = 16'sb1111111001110001;
        end
      4'b1101 :
        begin
          coeffTableOut5 = 16'sb0000000101111001;
        end
      4'b1110 :
        begin
          coeffTableOut5 = 16'sb1111111010011101;
        end
      4'b1111 :
        begin
          coeffTableOut5 = 16'sb0000000101001100;
        end
      default :
        begin
          coeffTableOut5 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP5_process
      if (enb) begin
        coeffTableRegP5_1 <= coeffTableOut5;
      end
    end



  // Coefficient table for multiplier4
  always @(rdAddr4) begin
    case ( rdAddr4)
      4'b0000 :
        begin
          coeffTableOut4 = 16'sb1111110101011001;
        end
      4'b0001 :
        begin
          coeffTableOut4 = 16'sb0000001010101111;
        end
      4'b0010 :
        begin
          coeffTableOut4 = 16'sb1111110101001010;
        end
      4'b0011 :
        begin
          coeffTableOut4 = 16'sb0000001010111011;
        end
      4'b0100 :
        begin
          coeffTableOut4 = 16'sb1111110101000001;
        end
      4'b0101 :
        begin
          coeffTableOut4 = 16'sb0000001011000010;
        end
      4'b0110 :
        begin
          coeffTableOut4 = 16'sb0111110100111110;
        end
      4'b0111 :
        begin
          coeffTableOut4 = 16'sb0000001011000010;
        end
      4'b1000 :
        begin
          coeffTableOut4 = 16'sb1111110101000001;
        end
      4'b1001 :
        begin
          coeffTableOut4 = 16'sb0000001010111011;
        end
      4'b1010 :
        begin
          coeffTableOut4 = 16'sb1111110101001010;
        end
      4'b1011 :
        begin
          coeffTableOut4 = 16'sb0000001010101111;
        end
      4'b1100 :
        begin
          coeffTableOut4 = 16'sb1111110101011001;
        end
      4'b1101 :
        begin
          coeffTableOut4 = 16'sb0000001010011101;
        end
      4'b1110 :
        begin
          coeffTableOut4 = 16'sb1111110101101110;
        end
      4'b1111 :
        begin
          coeffTableOut4 = 16'sb0000001010000101;
        end
      default :
        begin
          coeffTableOut4 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP4_process
      if (enb) begin
        coeffTableRegP4_1 <= coeffTableOut4;
      end
    end



  // Coefficient table for multiplier3
  always @(rdAddr3) begin
    case ( rdAddr3)
      4'b0000 :
        begin
          coeffTableOut3 = 16'sb1111111001110001;
        end
      4'b0001 :
        begin
          coeffTableOut3 = 16'sb0000000110100110;
        end
      4'b0010 :
        begin
          coeffTableOut3 = 16'sb1111111001000100;
        end
      4'b0011 :
        begin
          coeffTableOut3 = 16'sb0000000111010001;
        end
      4'b0100 :
        begin
          coeffTableOut3 = 16'sb1111111000011001;
        end
      4'b0101 :
        begin
          coeffTableOut3 = 16'sb0000000111111011;
        end
      4'b0110 :
        begin
          coeffTableOut3 = 16'sb1111110111110000;
        end
      4'b0111 :
        begin
          coeffTableOut3 = 16'sb0000001000100011;
        end
      4'b1000 :
        begin
          coeffTableOut3 = 16'sb1111110111001010;
        end
      4'b1001 :
        begin
          coeffTableOut3 = 16'sb0000001001001000;
        end
      4'b1010 :
        begin
          coeffTableOut3 = 16'sb1111110110100111;
        end
      4'b1011 :
        begin
          coeffTableOut3 = 16'sb0000001001101001;
        end
      4'b1100 :
        begin
          coeffTableOut3 = 16'sb1111110110001000;
        end
      4'b1101 :
        begin
          coeffTableOut3 = 16'sb0000001010000101;
        end
      4'b1110 :
        begin
          coeffTableOut3 = 16'sb1111110101101110;
        end
      4'b1111 :
        begin
          coeffTableOut3 = 16'sb0000001010011101;
        end
      default :
        begin
          coeffTableOut3 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP3_process
      if (enb) begin
        coeffTableRegP3_1 <= coeffTableOut3;
      end
    end



  // Coefficient table for multiplier2
  always @(rdAddr2) begin
    case ( rdAddr2)
      4'b0000 :
        begin
          coeffTableOut2 = 16'sb1111111110101011;
        end
      4'b0001 :
        begin
          coeffTableOut2 = 16'sb0000000001100011;
        end
      4'b0010 :
        begin
          coeffTableOut2 = 16'sb1111111110001101;
        end
      4'b0011 :
        begin
          coeffTableOut2 = 16'sb0000000010000100;
        end
      4'b0100 :
        begin
          coeffTableOut2 = 16'sb1111111101101011;
        end
      4'b0101 :
        begin
          coeffTableOut2 = 16'sb0000000010100111;
        end
      4'b0110 :
        begin
          coeffTableOut2 = 16'sb1111111101000110;
        end
      4'b0111 :
        begin
          coeffTableOut2 = 16'sb0000000011001101;
        end
      4'b1000 :
        begin
          coeffTableOut2 = 16'sb1111111100011111;
        end
      4'b1001 :
        begin
          coeffTableOut2 = 16'sb0000000011110110;
        end
      4'b1010 :
        begin
          coeffTableOut2 = 16'sb1111111011110101;
        end
      4'b1011 :
        begin
          coeffTableOut2 = 16'sb0000000100100001;
        end
      4'b1100 :
        begin
          coeffTableOut2 = 16'sb1111111011001010;
        end
      4'b1101 :
        begin
          coeffTableOut2 = 16'sb0000000101001100;
        end
      4'b1110 :
        begin
          coeffTableOut2 = 16'sb1111111010011101;
        end
      4'b1111 :
        begin
          coeffTableOut2 = 16'sb0000000101111001;
        end
      default :
        begin
          coeffTableOut2 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP2_process
      if (enb) begin
        coeffTableRegP2_1 <= coeffTableOut2;
      end
    end



  // Coefficient table for multiplier1
  always @(rdAddr1) begin
    case ( rdAddr1)
      4'b0000 :
        begin
          coeffTableOut1 = 16'sb0000000000100011;
        end
      4'b0001 :
        begin
          coeffTableOut1 = 16'sb1111111111011111;
        end
      4'b0010 :
        begin
          coeffTableOut1 = 16'sb0000000000011111;
        end
      4'b0011 :
        begin
          coeffTableOut1 = 16'sb1111111111100100;
        end
      4'b0100 :
        begin
          coeffTableOut1 = 16'sb0000000000011000;
        end
      4'b0101 :
        begin
          coeffTableOut1 = 16'sb1111111111101100;
        end
      4'b0110 :
        begin
          coeffTableOut1 = 16'sb0000000000001110;
        end
      4'b0111 :
        begin
          coeffTableOut1 = 16'sb1111111111111000;
        end
      4'b1000 :
        begin
          coeffTableOut1 = 16'sb0000000000000010;
        end
      4'b1001 :
        begin
          coeffTableOut1 = 16'sb0000000000000110;
        end
      4'b1010 :
        begin
          coeffTableOut1 = 16'sb1111111111110010;
        end
      4'b1011 :
        begin
          coeffTableOut1 = 16'sb0000000000011000;
        end
      4'b1100 :
        begin
          coeffTableOut1 = 16'sb1111111111011110;
        end
      4'b1101 :
        begin
          coeffTableOut1 = 16'sb0000000000101101;
        end
      4'b1110 :
        begin
          coeffTableOut1 = 16'sb1111111111000110;
        end
      4'b1111 :
        begin
          coeffTableOut1 = 16'sb0000000001000111;
        end
      default :
        begin
          coeffTableOut1 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP1_process
      if (enb) begin
        coeffTableRegP1_1 <= coeffTableOut1;
      end
    end



  // Coefficient table for multiplier0
  always @(rdAddr0_1) begin
    case ( rdAddr0_1)
      4'b0000 :
        begin
          coeffTableOut0 = 16'sb1111111111110010;
        end
      4'b0001 :
        begin
          coeffTableOut0 = 16'sb1111111110100010;
        end
      4'b0010 :
        begin
          coeffTableOut0 = 16'sb0000000000010011;
        end
      4'b0011 :
        begin
          coeffTableOut0 = 16'sb1111111111100001;
        end
      4'b0100 :
        begin
          coeffTableOut0 = 16'sb0000000000011011;
        end
      4'b0101 :
        begin
          coeffTableOut0 = 16'sb1111111111100011;
        end
      4'b0110 :
        begin
          coeffTableOut0 = 16'sb0000000000011110;
        end
      4'b0111 :
        begin
          coeffTableOut0 = 16'sb1111111111100000;
        end
      4'b1000 :
        begin
          coeffTableOut0 = 16'sb0000000000100001;
        end
      4'b1001 :
        begin
          coeffTableOut0 = 16'sb1111111111011110;
        end
      4'b1010 :
        begin
          coeffTableOut0 = 16'sb0000000000100011;
        end
      4'b1011 :
        begin
          coeffTableOut0 = 16'sb1111111111011100;
        end
      4'b1100 :
        begin
          coeffTableOut0 = 16'sb0000000000100101;
        end
      4'b1101 :
        begin
          coeffTableOut0 = 16'sb1111111111011011;
        end
      4'b1110 :
        begin
          coeffTableOut0 = 16'sb0000000000100101;
        end
      4'b1111 :
        begin
          coeffTableOut0 = 16'sb1111111111011100;
        end
      default :
        begin
          coeffTableOut0 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP0_process
      if (enb) begin
        coeffTableRegP0_1 <= coeffTableOut0;
      end
    end



  assign sumIn = 33'sh000000000;



  FilterTapSystolic_block3 u_filterTap0 (.clk(clk),
                                         .enb(enb),
                                         .din_re(delayLineDataOut0),  // sfix16_En15
                                         .coeff(coeffTableRegP0_1),  // sfix16_En15
                                         .sumIn(sumIn),  // sfix33_En30
                                         .sumOut(sumOut)  // sfix33_En30
                                         );

  FilterTapSystolic_block3 u_filterTap1 (.clk(clk),
                                         .enb(enb),
                                         .din_re(delayLineDataOut1),  // sfix16_En15
                                         .coeff(coeffTableRegP1_1),  // sfix16_En15
                                         .sumIn(sumOut),  // sfix33_En30
                                         .sumOut(sumOut_0)  // sfix33_En30
                                         );

  FilterTapSystolic_block3 u_filterTap2 (.clk(clk),
                                         .enb(enb),
                                         .din_re(delayLineDataOut2),  // sfix16_En15
                                         .coeff(coeffTableRegP2_1),  // sfix16_En15
                                         .sumIn(sumOut_0),  // sfix33_En30
                                         .sumOut(sumOut_1)  // sfix33_En30
                                         );

  FilterTapSystolic_block3 u_filterTap3 (.clk(clk),
                                         .enb(enb),
                                         .din_re(delayLineDataOut3),  // sfix16_En15
                                         .coeff(coeffTableRegP3_1),  // sfix16_En15
                                         .sumIn(sumOut_1),  // sfix33_En30
                                         .sumOut(sumOut_2)  // sfix33_En30
                                         );

  FilterTapSystolic_block3 u_filterTap4 (.clk(clk),
                                         .enb(enb),
                                         .din_re(delayLineDataOut4),  // sfix16_En15
                                         .coeff(coeffTableRegP4_1),  // sfix16_En15
                                         .sumIn(sumOut_2),  // sfix33_En30
                                         .sumOut(sumOut_3)  // sfix33_En30
                                         );

  FilterTapSystolic_block3 u_filterTap5 (.clk(clk),
                                         .enb(enb),
                                         .din_re(delayLineDataOut5),  // sfix16_En15
                                         .coeff(coeffTableRegP5_1),  // sfix16_En15
                                         .sumIn(sumOut_3),  // sfix33_En30
                                         .sumOut(sumOut_4)  // sfix33_En30
                                         );

  FilterTapSystolic_block3 u_filterTap6 (.clk(clk),
                                         .enb(enb),
                                         .din_re(delayLineDataOut6),  // sfix16_En15
                                         .coeff(coeffTableRegP6_1),  // sfix16_En15
                                         .sumIn(sumOut_4),  // sfix33_En30
                                         .sumOut(sumOut_5)  // sfix33_En30
                                         );

  FilterTapSystolic_block3 u_filterTap7 (.clk(clk),
                                         .enb(enb),
                                         .din_re(delayLineDataOut7),  // sfix16_En15
                                         .coeff(coeffTableRegP7_1),  // sfix16_En15
                                         .sumIn(sumOut_5),  // sfix33_En30
                                         .sumOut(sumOut_6)  // sfix33_En30
                                         );

  FilterTapSystolic_block3 u_filterTap8 (.clk(clk),
                                         .enb(enb),
                                         .din_re(delayLineDataOut8),  // sfix16_En15
                                         .coeff(coeffTableRegP8_1),  // sfix16_En15
                                         .sumIn(sumOut_6),  // sfix33_En30
                                         .sumOut(sumOut_7)  // sfix33_En30
                                         );

  always @(posedge clk or posedge reset)
    begin : sumOutReg_process
      if (reset == 1'b1) begin
        sumOutReg_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          sumOutReg_1 <= sumOut_7;
        end
      end
    end



  assign accSwitchOut = (accumulate == 1'b0 ? accDataOut_1 :
              accDataOut);



  assign accAdderOut = accSwitchOut + sumOutReg_1;



  always @(posedge clk or posedge reset)
    begin : accDataOut_2_process
      if (reset == 1'b1) begin
        accDataOut_1 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          accDataOut_1 <= accAdderOut;
        end
      end
    end



  assign converterOut = {accDataOut_1[32], accDataOut_1[32:16]};



  always @(posedge clk or posedge reset)
    begin : dout_re_process
      if (reset == 1'b1) begin
        dout_re_1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb && validOutLookahead_1) begin
          dout_re_1 <= converterOut;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : validOutLookahead_2_process
      if (reset == 1'b1) begin
        validOutLookahead_reg_1[0] <= 1'b0;
        validOutLookahead_reg_1[1] <= 1'b0;
        validOutLookahead_reg_1[2] <= 1'b0;
        validOutLookahead_reg_1[3] <= 1'b0;
        validOutLookahead_reg_1[4] <= 1'b0;
        validOutLookahead_reg_1[5] <= 1'b0;
        validOutLookahead_reg_1[6] <= 1'b0;
      end
      else begin
        if (enb) begin
          validOutLookahead_reg_1[0] <= validOutLookahead_reg_next_1[0];
          validOutLookahead_reg_1[1] <= validOutLookahead_reg_next_1[1];
          validOutLookahead_reg_1[2] <= validOutLookahead_reg_next_1[2];
          validOutLookahead_reg_1[3] <= validOutLookahead_reg_next_1[3];
          validOutLookahead_reg_1[4] <= validOutLookahead_reg_next_1[4];
          validOutLookahead_reg_1[5] <= validOutLookahead_reg_next_1[5];
          validOutLookahead_reg_1[6] <= validOutLookahead_reg_next_1[6];
        end
      end
    end

  assign validOutLookahead_3 = validOutLookahead_reg_1[6];
  assign validOutLookahead_reg_next_1[0] = delayLineShiftEn8_1;
  assign validOutLookahead_reg_next_1[1] = validOutLookahead_reg_1[0];
  assign validOutLookahead_reg_next_1[2] = validOutLookahead_reg_1[1];
  assign validOutLookahead_reg_next_1[3] = validOutLookahead_reg_1[2];
  assign validOutLookahead_reg_next_1[4] = validOutLookahead_reg_1[3];
  assign validOutLookahead_reg_next_1[5] = validOutLookahead_reg_1[4];
  assign validOutLookahead_reg_next_1[6] = validOutLookahead_reg_1[5];



  assign rdAddrEndNonZero_1 = rdAddr8 != 4'b0000;



  assign rdAddrEndZero_1 =  ~ rdAddrEndNonZero_1;



  always @(posedge clk or posedge reset)
    begin : finalSumValidPipe_1_process
      if (reset == 1'b1) begin
        finalSumValidPipe_reg_1[0] <= 1'b0;
        finalSumValidPipe_reg_1[1] <= 1'b0;
        finalSumValidPipe_reg_1[2] <= 1'b0;
        finalSumValidPipe_reg_1[3] <= 1'b0;
        finalSumValidPipe_reg_1[4] <= 1'b0;
        finalSumValidPipe_reg_1[5] <= 1'b0;
      end
      else begin
        if (enb) begin
          finalSumValidPipe_reg_1[0] <= finalSumValidPipe_reg_next_1[0];
          finalSumValidPipe_reg_1[1] <= finalSumValidPipe_reg_next_1[1];
          finalSumValidPipe_reg_1[2] <= finalSumValidPipe_reg_next_1[2];
          finalSumValidPipe_reg_1[3] <= finalSumValidPipe_reg_next_1[3];
          finalSumValidPipe_reg_1[4] <= finalSumValidPipe_reg_next_1[4];
          finalSumValidPipe_reg_1[5] <= finalSumValidPipe_reg_next_1[5];
        end
      end
    end

  assign accumulate_1 = finalSumValidPipe_reg_1[5];
  assign finalSumValidPipe_reg_next_1[0] = rdAddrEndZero_1;
  assign finalSumValidPipe_reg_next_1[1] = finalSumValidPipe_reg_1[0];
  assign finalSumValidPipe_reg_next_1[2] = finalSumValidPipe_reg_1[1];
  assign finalSumValidPipe_reg_next_1[3] = finalSumValidPipe_reg_1[2];
  assign finalSumValidPipe_reg_next_1[4] = finalSumValidPipe_reg_1[3];
  assign finalSumValidPipe_reg_next_1[5] = finalSumValidPipe_reg_1[4];



  assign accDataOut_3 = 33'sh000000000;



  Addressable_Delay_Line_block18 u_delayLine0_1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(enb),
                                                 .dataIn(dinSM_im),  // sfix16_En15
                                                 .wrEn(delayLineValidInP),
                                                 .wrAddr(wrAddrP),  // ufix4
                                                 .rdAddr(rdAddrDelayLine0),  // ufix4
                                                 .delayLineEnd(delayLineEnd0_1),  // sfix16_En15
                                                 .dataOut(delayLineDataOut0_1)  // sfix16_En15
                                                 );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn1_2_process
      if (reset == 1'b1) begin
        delayLineDataIn1_3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn1_3 <= delayLineEnd0_1;
        end
      end
    end



  Addressable_Delay_Line_block18 u_delayLine1_1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(enb),
                                                 .dataIn(delayLineDataIn1_3),  // sfix16_En15
                                                 .wrEn(delayLineShiftEn1_1),
                                                 .wrAddr(wrAddr1),  // ufix4
                                                 .rdAddr(rdAddrDelayLine1),  // ufix4
                                                 .delayLineEnd(delayLineEnd1_1),  // sfix16_En15
                                                 .dataOut(delayLineDataOut1_1)  // sfix16_En15
                                                 );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn2_2_process
      if (reset == 1'b1) begin
        delayLineDataIn2_3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn2_3 <= delayLineEnd1_1;
        end
      end
    end



  Addressable_Delay_Line_block18 u_delayLine2_1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(enb),
                                                 .dataIn(delayLineDataIn2_3),  // sfix16_En15
                                                 .wrEn(delayLineShiftEn2_1),
                                                 .wrAddr(wrAddr2),  // ufix4
                                                 .rdAddr(rdAddrDelayLine2),  // ufix4
                                                 .delayLineEnd(delayLineEnd2_1),  // sfix16_En15
                                                 .dataOut(delayLineDataOut2_1)  // sfix16_En15
                                                 );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn3_2_process
      if (reset == 1'b1) begin
        delayLineDataIn3_3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn3_3 <= delayLineEnd2_1;
        end
      end
    end



  Addressable_Delay_Line_block18 u_delayLine3_1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(enb),
                                                 .dataIn(delayLineDataIn3_3),  // sfix16_En15
                                                 .wrEn(delayLineShiftEn3_1),
                                                 .wrAddr(wrAddr3),  // ufix4
                                                 .rdAddr(rdAddrDelayLine3),  // ufix4
                                                 .delayLineEnd(delayLineEnd3_1),  // sfix16_En15
                                                 .dataOut(delayLineDataOut3_1)  // sfix16_En15
                                                 );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn4_2_process
      if (reset == 1'b1) begin
        delayLineDataIn4_3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn4_3 <= delayLineEnd3_1;
        end
      end
    end



  Addressable_Delay_Line_block18 u_delayLine4_1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(enb),
                                                 .dataIn(delayLineDataIn4_3),  // sfix16_En15
                                                 .wrEn(delayLineShiftEn4_1),
                                                 .wrAddr(wrAddr4),  // ufix4
                                                 .rdAddr(rdAddrDelayLine4),  // ufix4
                                                 .delayLineEnd(delayLineEnd4_1),  // sfix16_En15
                                                 .dataOut(delayLineDataOut4_1)  // sfix16_En15
                                                 );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn5_2_process
      if (reset == 1'b1) begin
        delayLineDataIn5_3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn5_3 <= delayLineEnd4_1;
        end
      end
    end



  Addressable_Delay_Line_block18 u_delayLine5_1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(enb),
                                                 .dataIn(delayLineDataIn5_3),  // sfix16_En15
                                                 .wrEn(delayLineShiftEn5_1),
                                                 .wrAddr(wrAddr5),  // ufix4
                                                 .rdAddr(rdAddrDelayLine5),  // ufix4
                                                 .delayLineEnd(delayLineEnd5_1),  // sfix16_En15
                                                 .dataOut(delayLineDataOut5_1)  // sfix16_En15
                                                 );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn6_2_process
      if (reset == 1'b1) begin
        delayLineDataIn6_3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn6_3 <= delayLineEnd5_1;
        end
      end
    end



  Addressable_Delay_Line_block18 u_delayLine6_1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(enb),
                                                 .dataIn(delayLineDataIn6_3),  // sfix16_En15
                                                 .wrEn(delayLineShiftEn6_1),
                                                 .wrAddr(wrAddr6),  // ufix4
                                                 .rdAddr(rdAddrDelayLine6),  // ufix4
                                                 .delayLineEnd(delayLineEnd6_1),  // sfix16_En15
                                                 .dataOut(delayLineDataOut6_1)  // sfix16_En15
                                                 );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn7_2_process
      if (reset == 1'b1) begin
        delayLineDataIn7_3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn7_3 <= delayLineEnd6_1;
        end
      end
    end



  Addressable_Delay_Line_block18 u_delayLine7_1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(enb),
                                                 .dataIn(delayLineDataIn7_3),  // sfix16_En15
                                                 .wrEn(delayLineShiftEn7_1),
                                                 .wrAddr(wrAddr7),  // ufix4
                                                 .rdAddr(rdAddrDelayLine7),  // ufix4
                                                 .delayLineEnd(delayLineEnd7_1),  // sfix16_En15
                                                 .dataOut(delayLineDataOut7_1)  // sfix16_En15
                                                 );

  always @(posedge clk or posedge reset)
    begin : delayLineDataIn8_2_process
      if (reset == 1'b1) begin
        delayLineDataIn8_3 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayLineDataIn8_3 <= delayLineEnd7_1;
        end
      end
    end



  Addressable_Delay_Line_block18 u_delayLine8_1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(enb),
                                                 .dataIn(delayLineDataIn8_3),  // sfix16_En15
                                                 .wrEn(delayLineShiftEn8_1),
                                                 .wrAddr(wrAddr8),  // ufix4
                                                 .rdAddr(rdAddrDelayLine8),  // ufix4
                                                 .delayLineEnd(delayLineEnd8deadOut_1),  // sfix16_En15
                                                 .dataOut(delayLineDataOut8_1)  // sfix16_En15
                                                 );

  // Coefficient table for multiplier8
  always @(rdAddr8) begin
    case ( rdAddr8)
      4'b0000 :
        begin
          coeffTableOut8_1 = 16'sb0000000000100101;
        end
      4'b0001 :
        begin
          coeffTableOut8_1 = 16'sb1111111111011100;
        end
      4'b0010 :
        begin
          coeffTableOut8_1 = 16'sb0000000000100011;
        end
      4'b0011 :
        begin
          coeffTableOut8_1 = 16'sb1111111111011110;
        end
      4'b0100 :
        begin
          coeffTableOut8_1 = 16'sb0000000000100001;
        end
      4'b0101 :
        begin
          coeffTableOut8_1 = 16'sb1111111111100000;
        end
      4'b0110 :
        begin
          coeffTableOut8_1 = 16'sb0000000000011110;
        end
      4'b0111 :
        begin
          coeffTableOut8_1 = 16'sb1111111111100011;
        end
      4'b1000 :
        begin
          coeffTableOut8_1 = 16'sb0000000000011011;
        end
      4'b1001 :
        begin
          coeffTableOut8_1 = 16'sb1111111111100001;
        end
      4'b1010 :
        begin
          coeffTableOut8_1 = 16'sb0000000000010011;
        end
      4'b1011 :
        begin
          coeffTableOut8_1 = 16'sb1111111110100010;
        end
      4'b1100 :
        begin
          coeffTableOut8_1 = 16'sb1111111111110010;
        end
      4'b1101 :
        begin
          coeffTableOut8_1 = 16'sb0000000000000000;
        end
      4'b1110 :
        begin
          coeffTableOut8_1 = 16'sb0000000000000000;
        end
      4'b1111 :
        begin
          coeffTableOut8_1 = 16'sb0000000000000000;
        end
      default :
        begin
          coeffTableOut8_1 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP8_2_process
      if (enb) begin
        coeffTableRegP8_3 <= coeffTableOut8_1;
      end
    end



  // Coefficient table for multiplier7
  always @(rdAddr7) begin
    case ( rdAddr7)
      4'b0000 :
        begin
          coeffTableOut7_1 = 16'sb1111111111011110;
        end
      4'b0001 :
        begin
          coeffTableOut7_1 = 16'sb0000000000011000;
        end
      4'b0010 :
        begin
          coeffTableOut7_1 = 16'sb1111111111110010;
        end
      4'b0011 :
        begin
          coeffTableOut7_1 = 16'sb0000000000000110;
        end
      4'b0100 :
        begin
          coeffTableOut7_1 = 16'sb0000000000000010;
        end
      4'b0101 :
        begin
          coeffTableOut7_1 = 16'sb1111111111111000;
        end
      4'b0110 :
        begin
          coeffTableOut7_1 = 16'sb0000000000001110;
        end
      4'b0111 :
        begin
          coeffTableOut7_1 = 16'sb1111111111101100;
        end
      4'b1000 :
        begin
          coeffTableOut7_1 = 16'sb0000000000011000;
        end
      4'b1001 :
        begin
          coeffTableOut7_1 = 16'sb1111111111100100;
        end
      4'b1010 :
        begin
          coeffTableOut7_1 = 16'sb0000000000011111;
        end
      4'b1011 :
        begin
          coeffTableOut7_1 = 16'sb1111111111011111;
        end
      4'b1100 :
        begin
          coeffTableOut7_1 = 16'sb0000000000100011;
        end
      4'b1101 :
        begin
          coeffTableOut7_1 = 16'sb1111111111011100;
        end
      4'b1110 :
        begin
          coeffTableOut7_1 = 16'sb0000000000100101;
        end
      4'b1111 :
        begin
          coeffTableOut7_1 = 16'sb1111111111011011;
        end
      default :
        begin
          coeffTableOut7_1 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP7_2_process
      if (enb) begin
        coeffTableRegP7_3 <= coeffTableOut7_1;
      end
    end



  // Coefficient table for multiplier6
  always @(rdAddr6) begin
    case ( rdAddr6)
      4'b0000 :
        begin
          coeffTableOut6_1 = 16'sb1111111011001010;
        end
      4'b0001 :
        begin
          coeffTableOut6_1 = 16'sb0000000100100001;
        end
      4'b0010 :
        begin
          coeffTableOut6_1 = 16'sb1111111011110101;
        end
      4'b0011 :
        begin
          coeffTableOut6_1 = 16'sb0000000011110110;
        end
      4'b0100 :
        begin
          coeffTableOut6_1 = 16'sb1111111100011111;
        end
      4'b0101 :
        begin
          coeffTableOut6_1 = 16'sb0000000011001101;
        end
      4'b0110 :
        begin
          coeffTableOut6_1 = 16'sb1111111101000110;
        end
      4'b0111 :
        begin
          coeffTableOut6_1 = 16'sb0000000010100111;
        end
      4'b1000 :
        begin
          coeffTableOut6_1 = 16'sb1111111101101011;
        end
      4'b1001 :
        begin
          coeffTableOut6_1 = 16'sb0000000010000100;
        end
      4'b1010 :
        begin
          coeffTableOut6_1 = 16'sb1111111110001101;
        end
      4'b1011 :
        begin
          coeffTableOut6_1 = 16'sb0000000001100011;
        end
      4'b1100 :
        begin
          coeffTableOut6_1 = 16'sb1111111110101011;
        end
      4'b1101 :
        begin
          coeffTableOut6_1 = 16'sb0000000001000111;
        end
      4'b1110 :
        begin
          coeffTableOut6_1 = 16'sb1111111111000110;
        end
      4'b1111 :
        begin
          coeffTableOut6_1 = 16'sb0000000000101101;
        end
      default :
        begin
          coeffTableOut6_1 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP6_2_process
      if (enb) begin
        coeffTableRegP6_3 <= coeffTableOut6_1;
      end
    end



  // Coefficient table for multiplier5
  always @(rdAddr5) begin
    case ( rdAddr5)
      4'b0000 :
        begin
          coeffTableOut5_1 = 16'sb1111110110001000;
        end
      4'b0001 :
        begin
          coeffTableOut5_1 = 16'sb0000001001101001;
        end
      4'b0010 :
        begin
          coeffTableOut5_1 = 16'sb1111110110100111;
        end
      4'b0011 :
        begin
          coeffTableOut5_1 = 16'sb0000001001001000;
        end
      4'b0100 :
        begin
          coeffTableOut5_1 = 16'sb1111110111001010;
        end
      4'b0101 :
        begin
          coeffTableOut5_1 = 16'sb0000001000100011;
        end
      4'b0110 :
        begin
          coeffTableOut5_1 = 16'sb1111110111110000;
        end
      4'b0111 :
        begin
          coeffTableOut5_1 = 16'sb0000000111111011;
        end
      4'b1000 :
        begin
          coeffTableOut5_1 = 16'sb1111111000011001;
        end
      4'b1001 :
        begin
          coeffTableOut5_1 = 16'sb0000000111010001;
        end
      4'b1010 :
        begin
          coeffTableOut5_1 = 16'sb1111111001000100;
        end
      4'b1011 :
        begin
          coeffTableOut5_1 = 16'sb0000000110100110;
        end
      4'b1100 :
        begin
          coeffTableOut5_1 = 16'sb1111111001110001;
        end
      4'b1101 :
        begin
          coeffTableOut5_1 = 16'sb0000000101111001;
        end
      4'b1110 :
        begin
          coeffTableOut5_1 = 16'sb1111111010011101;
        end
      4'b1111 :
        begin
          coeffTableOut5_1 = 16'sb0000000101001100;
        end
      default :
        begin
          coeffTableOut5_1 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP5_2_process
      if (enb) begin
        coeffTableRegP5_3 <= coeffTableOut5_1;
      end
    end



  // Coefficient table for multiplier4
  always @(rdAddr4) begin
    case ( rdAddr4)
      4'b0000 :
        begin
          coeffTableOut4_1 = 16'sb1111110101011001;
        end
      4'b0001 :
        begin
          coeffTableOut4_1 = 16'sb0000001010101111;
        end
      4'b0010 :
        begin
          coeffTableOut4_1 = 16'sb1111110101001010;
        end
      4'b0011 :
        begin
          coeffTableOut4_1 = 16'sb0000001010111011;
        end
      4'b0100 :
        begin
          coeffTableOut4_1 = 16'sb1111110101000001;
        end
      4'b0101 :
        begin
          coeffTableOut4_1 = 16'sb0000001011000010;
        end
      4'b0110 :
        begin
          coeffTableOut4_1 = 16'sb0111110100111110;
        end
      4'b0111 :
        begin
          coeffTableOut4_1 = 16'sb0000001011000010;
        end
      4'b1000 :
        begin
          coeffTableOut4_1 = 16'sb1111110101000001;
        end
      4'b1001 :
        begin
          coeffTableOut4_1 = 16'sb0000001010111011;
        end
      4'b1010 :
        begin
          coeffTableOut4_1 = 16'sb1111110101001010;
        end
      4'b1011 :
        begin
          coeffTableOut4_1 = 16'sb0000001010101111;
        end
      4'b1100 :
        begin
          coeffTableOut4_1 = 16'sb1111110101011001;
        end
      4'b1101 :
        begin
          coeffTableOut4_1 = 16'sb0000001010011101;
        end
      4'b1110 :
        begin
          coeffTableOut4_1 = 16'sb1111110101101110;
        end
      4'b1111 :
        begin
          coeffTableOut4_1 = 16'sb0000001010000101;
        end
      default :
        begin
          coeffTableOut4_1 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP4_2_process
      if (enb) begin
        coeffTableRegP4_3 <= coeffTableOut4_1;
      end
    end



  // Coefficient table for multiplier3
  always @(rdAddr3) begin
    case ( rdAddr3)
      4'b0000 :
        begin
          coeffTableOut3_1 = 16'sb1111111001110001;
        end
      4'b0001 :
        begin
          coeffTableOut3_1 = 16'sb0000000110100110;
        end
      4'b0010 :
        begin
          coeffTableOut3_1 = 16'sb1111111001000100;
        end
      4'b0011 :
        begin
          coeffTableOut3_1 = 16'sb0000000111010001;
        end
      4'b0100 :
        begin
          coeffTableOut3_1 = 16'sb1111111000011001;
        end
      4'b0101 :
        begin
          coeffTableOut3_1 = 16'sb0000000111111011;
        end
      4'b0110 :
        begin
          coeffTableOut3_1 = 16'sb1111110111110000;
        end
      4'b0111 :
        begin
          coeffTableOut3_1 = 16'sb0000001000100011;
        end
      4'b1000 :
        begin
          coeffTableOut3_1 = 16'sb1111110111001010;
        end
      4'b1001 :
        begin
          coeffTableOut3_1 = 16'sb0000001001001000;
        end
      4'b1010 :
        begin
          coeffTableOut3_1 = 16'sb1111110110100111;
        end
      4'b1011 :
        begin
          coeffTableOut3_1 = 16'sb0000001001101001;
        end
      4'b1100 :
        begin
          coeffTableOut3_1 = 16'sb1111110110001000;
        end
      4'b1101 :
        begin
          coeffTableOut3_1 = 16'sb0000001010000101;
        end
      4'b1110 :
        begin
          coeffTableOut3_1 = 16'sb1111110101101110;
        end
      4'b1111 :
        begin
          coeffTableOut3_1 = 16'sb0000001010011101;
        end
      default :
        begin
          coeffTableOut3_1 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP3_2_process
      if (enb) begin
        coeffTableRegP3_3 <= coeffTableOut3_1;
      end
    end



  // Coefficient table for multiplier2
  always @(rdAddr2) begin
    case ( rdAddr2)
      4'b0000 :
        begin
          coeffTableOut2_1 = 16'sb1111111110101011;
        end
      4'b0001 :
        begin
          coeffTableOut2_1 = 16'sb0000000001100011;
        end
      4'b0010 :
        begin
          coeffTableOut2_1 = 16'sb1111111110001101;
        end
      4'b0011 :
        begin
          coeffTableOut2_1 = 16'sb0000000010000100;
        end
      4'b0100 :
        begin
          coeffTableOut2_1 = 16'sb1111111101101011;
        end
      4'b0101 :
        begin
          coeffTableOut2_1 = 16'sb0000000010100111;
        end
      4'b0110 :
        begin
          coeffTableOut2_1 = 16'sb1111111101000110;
        end
      4'b0111 :
        begin
          coeffTableOut2_1 = 16'sb0000000011001101;
        end
      4'b1000 :
        begin
          coeffTableOut2_1 = 16'sb1111111100011111;
        end
      4'b1001 :
        begin
          coeffTableOut2_1 = 16'sb0000000011110110;
        end
      4'b1010 :
        begin
          coeffTableOut2_1 = 16'sb1111111011110101;
        end
      4'b1011 :
        begin
          coeffTableOut2_1 = 16'sb0000000100100001;
        end
      4'b1100 :
        begin
          coeffTableOut2_1 = 16'sb1111111011001010;
        end
      4'b1101 :
        begin
          coeffTableOut2_1 = 16'sb0000000101001100;
        end
      4'b1110 :
        begin
          coeffTableOut2_1 = 16'sb1111111010011101;
        end
      4'b1111 :
        begin
          coeffTableOut2_1 = 16'sb0000000101111001;
        end
      default :
        begin
          coeffTableOut2_1 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP2_2_process
      if (enb) begin
        coeffTableRegP2_3 <= coeffTableOut2_1;
      end
    end



  // Coefficient table for multiplier1
  always @(rdAddr1) begin
    case ( rdAddr1)
      4'b0000 :
        begin
          coeffTableOut1_1 = 16'sb0000000000100011;
        end
      4'b0001 :
        begin
          coeffTableOut1_1 = 16'sb1111111111011111;
        end
      4'b0010 :
        begin
          coeffTableOut1_1 = 16'sb0000000000011111;
        end
      4'b0011 :
        begin
          coeffTableOut1_1 = 16'sb1111111111100100;
        end
      4'b0100 :
        begin
          coeffTableOut1_1 = 16'sb0000000000011000;
        end
      4'b0101 :
        begin
          coeffTableOut1_1 = 16'sb1111111111101100;
        end
      4'b0110 :
        begin
          coeffTableOut1_1 = 16'sb0000000000001110;
        end
      4'b0111 :
        begin
          coeffTableOut1_1 = 16'sb1111111111111000;
        end
      4'b1000 :
        begin
          coeffTableOut1_1 = 16'sb0000000000000010;
        end
      4'b1001 :
        begin
          coeffTableOut1_1 = 16'sb0000000000000110;
        end
      4'b1010 :
        begin
          coeffTableOut1_1 = 16'sb1111111111110010;
        end
      4'b1011 :
        begin
          coeffTableOut1_1 = 16'sb0000000000011000;
        end
      4'b1100 :
        begin
          coeffTableOut1_1 = 16'sb1111111111011110;
        end
      4'b1101 :
        begin
          coeffTableOut1_1 = 16'sb0000000000101101;
        end
      4'b1110 :
        begin
          coeffTableOut1_1 = 16'sb1111111111000110;
        end
      4'b1111 :
        begin
          coeffTableOut1_1 = 16'sb0000000001000111;
        end
      default :
        begin
          coeffTableOut1_1 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP1_2_process
      if (enb) begin
        coeffTableRegP1_3 <= coeffTableOut1_1;
      end
    end



  // Coefficient table for multiplier0
  always @(rdAddr0_1) begin
    case ( rdAddr0_1)
      4'b0000 :
        begin
          coeffTableOut0_1 = 16'sb1111111111110010;
        end
      4'b0001 :
        begin
          coeffTableOut0_1 = 16'sb1111111110100010;
        end
      4'b0010 :
        begin
          coeffTableOut0_1 = 16'sb0000000000010011;
        end
      4'b0011 :
        begin
          coeffTableOut0_1 = 16'sb1111111111100001;
        end
      4'b0100 :
        begin
          coeffTableOut0_1 = 16'sb0000000000011011;
        end
      4'b0101 :
        begin
          coeffTableOut0_1 = 16'sb1111111111100011;
        end
      4'b0110 :
        begin
          coeffTableOut0_1 = 16'sb0000000000011110;
        end
      4'b0111 :
        begin
          coeffTableOut0_1 = 16'sb1111111111100000;
        end
      4'b1000 :
        begin
          coeffTableOut0_1 = 16'sb0000000000100001;
        end
      4'b1001 :
        begin
          coeffTableOut0_1 = 16'sb1111111111011110;
        end
      4'b1010 :
        begin
          coeffTableOut0_1 = 16'sb0000000000100011;
        end
      4'b1011 :
        begin
          coeffTableOut0_1 = 16'sb1111111111011100;
        end
      4'b1100 :
        begin
          coeffTableOut0_1 = 16'sb0000000000100101;
        end
      4'b1101 :
        begin
          coeffTableOut0_1 = 16'sb1111111111011011;
        end
      4'b1110 :
        begin
          coeffTableOut0_1 = 16'sb0000000000100101;
        end
      4'b1111 :
        begin
          coeffTableOut0_1 = 16'sb1111111111011100;
        end
      default :
        begin
          coeffTableOut0_1 = 16'sb0000000000000000;
        end
    endcase
  end



  always @(posedge clk)
    begin : coeffTableRegP0_2_process
      if (enb) begin
        coeffTableRegP0_3 <= coeffTableOut0_1;
      end
    end



  assign sumIn_1 = 33'sh000000000;



  FilterTapSystolic_block4 u_filterTap0_1 (.clk(clk),
                                           .enb(enb),
                                           .din_im(delayLineDataOut0_1),  // sfix16_En15
                                           .coeff(coeffTableRegP0_3),  // sfix16_En15
                                           .sumIn(sumIn_1),  // sfix33_En30
                                           .sumOut(sumOut_8)  // sfix33_En30
                                           );

  FilterTapSystolic_block4 u_filterTap1_1 (.clk(clk),
                                           .enb(enb),
                                           .din_im(delayLineDataOut1_1),  // sfix16_En15
                                           .coeff(coeffTableRegP1_3),  // sfix16_En15
                                           .sumIn(sumOut_8),  // sfix33_En30
                                           .sumOut(sumOut_0_1)  // sfix33_En30
                                           );

  FilterTapSystolic_block4 u_filterTap2_1 (.clk(clk),
                                           .enb(enb),
                                           .din_im(delayLineDataOut2_1),  // sfix16_En15
                                           .coeff(coeffTableRegP2_3),  // sfix16_En15
                                           .sumIn(sumOut_0_1),  // sfix33_En30
                                           .sumOut(sumOut_1_1)  // sfix33_En30
                                           );

  FilterTapSystolic_block4 u_filterTap3_1 (.clk(clk),
                                           .enb(enb),
                                           .din_im(delayLineDataOut3_1),  // sfix16_En15
                                           .coeff(coeffTableRegP3_3),  // sfix16_En15
                                           .sumIn(sumOut_1_1),  // sfix33_En30
                                           .sumOut(sumOut_2_1)  // sfix33_En30
                                           );

  FilterTapSystolic_block4 u_filterTap4_1 (.clk(clk),
                                           .enb(enb),
                                           .din_im(delayLineDataOut4_1),  // sfix16_En15
                                           .coeff(coeffTableRegP4_3),  // sfix16_En15
                                           .sumIn(sumOut_2_1),  // sfix33_En30
                                           .sumOut(sumOut_3_1)  // sfix33_En30
                                           );

  FilterTapSystolic_block4 u_filterTap5_1 (.clk(clk),
                                           .enb(enb),
                                           .din_im(delayLineDataOut5_1),  // sfix16_En15
                                           .coeff(coeffTableRegP5_3),  // sfix16_En15
                                           .sumIn(sumOut_3_1),  // sfix33_En30
                                           .sumOut(sumOut_4_1)  // sfix33_En30
                                           );

  FilterTapSystolic_block4 u_filterTap6_1 (.clk(clk),
                                           .enb(enb),
                                           .din_im(delayLineDataOut6_1),  // sfix16_En15
                                           .coeff(coeffTableRegP6_3),  // sfix16_En15
                                           .sumIn(sumOut_4_1),  // sfix33_En30
                                           .sumOut(sumOut_5_1)  // sfix33_En30
                                           );

  FilterTapSystolic_block4 u_filterTap7_1 (.clk(clk),
                                           .enb(enb),
                                           .din_im(delayLineDataOut7_1),  // sfix16_En15
                                           .coeff(coeffTableRegP7_3),  // sfix16_En15
                                           .sumIn(sumOut_5_1),  // sfix33_En30
                                           .sumOut(sumOut_6_1)  // sfix33_En30
                                           );

  FilterTapSystolic_block4 u_filterTap8_1 (.clk(clk),
                                           .enb(enb),
                                           .din_im(delayLineDataOut8_1),  // sfix16_En15
                                           .coeff(coeffTableRegP8_3),  // sfix16_En15
                                           .sumIn(sumOut_6_1),  // sfix33_En30
                                           .sumOut(sumOut_7_1)  // sfix33_En30
                                           );

  always @(posedge clk or posedge reset)
    begin : sumOutReg_2_process
      if (reset == 1'b1) begin
        sumOutReg_3 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          sumOutReg_3 <= sumOut_7_1;
        end
      end
    end



  assign accSwitchOut_1 = (accumulate_1 == 1'b0 ? accDataOut_4 :
              accDataOut_3);



  assign accAdderOut_1 = accSwitchOut_1 + sumOutReg_3;



  always @(posedge clk or posedge reset)
    begin : accDataOut_5_process
      if (reset == 1'b1) begin
        accDataOut_4 <= 33'sh000000000;
      end
      else begin
        if (enb) begin
          accDataOut_4 <= accAdderOut_1;
        end
      end
    end



  assign converterOut_1 = {accDataOut_4[32], accDataOut_4[32:16]};



  always @(posedge clk or posedge reset)
    begin : dout_im_process
      if (reset == 1'b1) begin
        dout_im_1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb && validOutLookahead_3) begin
          dout_im_1 <= converterOut_1;
        end
      end
    end



  assign dataZero = 18'sb000000000000000000;



  assign dataZero_dtc_re = dataZero;
  assign dataZero_dtc_im = 18'sb000000000000000000;



  assign dout_cmplxSW_re = (notValid == 1'b0 ? dout_re_1 :
              dataZero_dtc_re);
  assign dout_cmplxSW_im = (notValid == 1'b0 ? dout_im_1 :
              dataZero_dtc_im);



  assign dataOut_re = dout_cmplxSW_re;

  assign dataOut_im = dout_cmplxSW_im;

  assign validOut = vldOut_1;

endmodule  // FIRFilter2_block1

