// -------------------------------------------------------------
// 
// File Name: D:\OFDM\HDLImplementationOfDUCForLTEExample(Single Tone Output)\HDLImplementationOfDUCForLTEExample\hdlsrc\complex_upsampler\DUCforLTEHDL\Gain_Correction.v
// Created: 2023-05-25 17:45:33
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Gain_Correction
// Source Path: DUCforLTEHDL/HDL_DUC/Gain Correction
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Gain_Correction
          (dataIn_re,
           dataIn_im,
           dataOut_re,
           dataOut_im);


  input   signed [17:0] dataIn_re;  // sfix18_En12
  input   signed [17:0] dataIn_im;  // sfix18_En12
  output  signed [17:0] dataOut_re;  // sfix18_En14
  output  signed [17:0] dataOut_im;  // sfix18_En14


  wire signed [17:0] Data_Type_Conversion_out1_re;  // sfix18_En14
  wire signed [17:0] Data_Type_Conversion_out1_im;  // sfix18_En14

  // Divide by 4096
  // To right-shift by 12 bits, reinterpret the number to have 
  // 20 fractional bits rather than 8 fractional bits.


  assign Data_Type_Conversion_out1_re = dataIn_re;
  assign Data_Type_Conversion_out1_im = dataIn_im;



  assign dataOut_re = Data_Type_Conversion_out1_re;

  assign dataOut_im = Data_Type_Conversion_out1_im;

endmodule  // Gain_Correction

