vlib work
vlog  HDL_DUC_tc.v
vlog  Gain_Correction.v
vlog  Mixer.v
vlog  FirRdyLogic.v
vlog  SimpleDualPortRAM_generic.v
vlog  Addressable_Delay_Line.v
vlog  FilterTapSystolic.v
vlog  Addressable_Delay_Line_block.v
vlog  FilterTapSystolic_block.v
vlog  FIRFilter1.v
vlog  FirRdyLogic_block.v
vlog  Addressable_Delay_Line_block1.v
vlog  FilterTapSystolic_block1.v
vlog  Addressable_Delay_Line_block2.v
vlog  FilterTapSystolic_block2.v
vlog  FIRFilter2.v
vlog  CIC_Compensation_Interpolator.v
vlog  rdySection.v
vlog  cSection.v
vlog  usSection.v
vlog  iSection.v
vlog  gcSection.v
vlog  castSection.v
vlog  CICInterpolator.v
vlog  FirRdyLogic_block1.v
vlog  Addressable_Delay_Line_block3.v
vlog  Addressable_Delay_Line_block4.v
vlog  FilterTapSystolicPreAdd.v
vlog  Addressable_Delay_Line_block5.v
vlog  Addressable_Delay_Line_block6.v
vlog  FilterTapSystolicPreAdd_block.v
vlog  FIRFilter1_block.v
vlog  FirRdyLogic_block2.v
vlog  Addressable_Delay_Line_block7.v
vlog  Addressable_Delay_Line_block8.v
vlog  FIRFilter2_block.v
vlog  Halfband_Interpolator.v
vlog  FirRdyLogic_block3.v
vlog  Addressable_Delay_Line_block9.v
vlog  Addressable_Delay_Line_block10.v
vlog  Addressable_Delay_Line_block11.v
vlog  Addressable_Delay_Line_block12.v
vlog  FilterTapSystolicPreAdd_block1.v
vlog  Addressable_Delay_Line_block13.v
vlog  Addressable_Delay_Line_block14.v
vlog  Addressable_Delay_Line_block15.v
vlog  Addressable_Delay_Line_block16.v
vlog  FilterTapSystolicPreAdd_block2.v
vlog  FIRFilter1_block1.v
vlog  FirRdyLogic_block4.v
vlog  Addressable_Delay_Line_block17.v
vlog  FilterTapSystolic_block3.v
vlog  Addressable_Delay_Line_block18.v
vlog  FilterTapSystolic_block4.v
vlog  FIRFilter2_block1.v
vlog  Lowpass_Interpolator.v
vlog  DitherGen.v
vlog  LookUpTableGen.v
vlog  WaveformGen.v
vlog  NCO.v
vlog  HDL_DUC.v
